Fix hover text labels in Table menu for consistency and clarity
CollaboraOnline/online pull request #10076
Opened 2024-09-18 17:50 UTC by Darshan-upadhyay1110

Corrected the hover text labels in the Table menu to ensure they accurately describe the actions they represent:
- Updated "Cell" to "Select Cell"
- Updated "Table" to "Delete Table" and "Select Table" accordingly
- Updated "Row" to "Select Row"
- Updated "Column" to "Select Column"
- Updated "Columns" and "Rows" to "Delete Columns" and "Delete Rows"

This resolves inconsistencies and improves user experience by providing clearer descriptions for each menu action.

Change-Id: Iec2f04434eb175cbf5a38a5b91dd3e4e896ce7e9

* Resolves: # 
* Target version: master 

### Summary

### TODO

- [ ] ...

### Checklist

- [ ] I have run `make prettier-write` and formatted the code.
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

2024-09-18 20:30 UTC, timar requested changes
1st line of unocommands.js:
`// Don't modify, generated using unocommands.py`

2024-09-19 06:06 UTC, eszkadev commented on browser/src/unocommands.js
> +	'DeleteColumns':{global:{context:_('Delete selected columns'),menu:_('Delete ~Columns'),},text:{context:_('Delete selected columns'),menu:_('Delete ~Columns'),},},
I see duplicated `menu` here. Did you use script to generate this? I think it shouldn't be modfied manually.
If we use wrong text somewhere, then might be usefult to add the type specifier so we will use other variant:
`_UNO('.uno:PageDown', 'text', here some variant option)`
https://github.com/CollaboraOnline/online/blob/e07a403d0aa2017d4c6ccf69c05e56d466e9ead5/browser/src/unocommands.js#L528

2024-09-19 08:00 UTC, timar approved these changes

2024-09-19 12:32 UTC, merged

2024-10-03 12:18 UTC, Darshan-upadhyay1110 commented
> The “Column Before” button does “Column After”, and the “Column After” button does “Column Before”, so should these buttons functions be swapped around?

Hii @rpear i just tested this and it does work okay as expected. "Column Before" insert column before in table for writer and same is okay for  "Column After". 

Can you please explain what is wrong here ?

2024-10-03 12:26 UTC, Darshan-upadhyay1110 commented
> Could the buttons be renamed from “Column Before” to “Insert Column Before,” and “Column After” to “Insert Column After”? 

> Additionally, while “Rows Above” and “Rows Below” function correctly, could we rename these buttons to “Insert Rows Above” and “Insert Rows Below,” respectively? 

Absolutely, we can do that! :)

> I could create a ticket if needed.

Thanks, @rpear! It would be fantastic if you could create one. If you’re interested in tackling this issue, I can provide you with code pointers. It’s a straightforward fix! The PR itself serves as a code pointer; just follow what I did in that commit, and you’ll be able to resolve the issue easily.

2024-10-03 12:45 UTC, rpear commented
Hi Darshan,  OK I'd like to have a go at that, I guess there's no urgency.
I'll get back to you.  Rob

On Thu, 3 Oct 2024 at 22:27, Darshan-Upadhyay ***@***.***>
wrote:

> Could the buttons be renamed from “Column Before” to “Insert Column
> Before,” and “Column After” to “Insert Column After”?
>
> Additionally, while “Rows Above” and “Rows Below” function correctly,
> could we rename these buttons to “Insert Rows Above” and “Insert Rows
> Below,” respectively?
>
> Absolutely, we can do that! :)
>
> I could create a ticket if needed.
>
> Thanks, @rpear <https://github.com/rpear>! It would be fantastic if you
> could create one. If you’re interested in tackling this issue, I can
> provide you with code pointers. It’s a straightforward fix! The PR itself
> serves as a code pointer; just follow what I did in that commit, and you’ll
> be able to resolve the issue easily.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/CollaboraOnline/online/pull/10076#issuecomment-2391292707>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATIMIR63MHZWMQHIOYKNG3TZZUZ2PAVCNFSM6AAAAABOOHARYCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGOJRGI4TENZQG4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-10-04 09:56 UTC, rpear commented
See https://github.com/CollaboraOnline/online/issues/10175
Fix more hover text labels in Table menu for consistency and clarity #10175