fix: show error to user when online fails to download clipboard on pa…
CollaboraOnline/online pull request #10348
Opened 2024-10-28 10:56 UTC by Rash419

…sting

follow up of e9a0eeb78dcc

Change-Id: I7c3cf0cbb0b0b945b6144d9b2b6a2d8cf02a0a2c

* Target version: master

2024-10-28 10:57 UTC, Rash419 commented
Don't merge until I say so I am building docker to test the functionality in cluster environment

2024-10-28 11:05 UTC, eszkadev approved these changes

2024-10-28 13:26 UTC, Rash419 commented
Okay to merge now, it works as expected:
![image](https://github.com/user-attachments/assets/17c6bb93-eb10-41c1-9c1f-32703b063462)

2024-10-31 08:02 UTC, eszkadev requested changes

2024-10-31 08:02 UTC, eszkadev commented on browser/src/map/Clipboard.js
> +					const reader = new FileReader();
this code is duplicated, please create shared function somewhere

2024-10-31 08:02 UTC, eszkadev commented on browser/src/map/Clipboard.js
> +					const reader = new FileReader();
eg. in docstatefunctions.js then it is accessible using app.nameOfFunction

2024-10-31 11:12 UTC, eszkadev approved these changes

2024-11-01 08:09 UTC, merged