Add concurrent TCP connections to 'getMetrics' REST endpoint
CollaboraOnline/online pull request #10455
Opened 2024-11-09 11:19 UTC by sgothel

* Resolves: # 
* Target version: master 

### Summary
Add max/used concurrent TCP connections to Prometheus text-based 'getMetrics' REST endpoint

### Checklist

- [ ] I have run `make prettier-write` and formatted the code.
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

2024-11-11 23:09 UTC, sgothel commented on common/Util-desktop.cpp
> +        while (sizeof(data)-consumed-1 /* ex-EOS */ > 0)
negative value never intended, but `>0` or `!=0` is correct here.

2024-11-11 23:13 UTC, sgothel commented
Cleaned up branch rebased tree, i.e. PR #10375 -> #10455 -> #10456

2024-11-13 12:58 UTC, caolanm commented
In this PR the first three patches are already in https://github.com/CollaboraOnline/online/pull/10375 and that last one is AFAICS independent of the others in the sense that it builds without them, so we could drop those here and just get that piece in without requiring the rest so this could be merged independently

2024-11-13 13:45 UTC, sgothel commented
PR [#10480](https://github.com/CollaboraOnline/online/pull/10480) -> [#10455](https://github.com/CollaboraOnline/online/pull/10455) -> [#10456](https://github.com/CollaboraOnline/online/pull/10456)

2024-11-13 14:01 UTC, sgothel commented on wsd/metrics.txt
> +    global_host_tcp_connections - Total host concurrent TCP connections.
Yeah well .. that is surely a more relaxed and flexible way of putting it. May or may not depend on the outcome of our little debate re https://github.com/CollaboraOnline/online/pull/10375#discussion_r1840102237.

Will reword it.

2024-11-13 14:09 UTC, mmeeks requested changes
Fine - but I don't want to have to re-review and re-approve the Closed patch underneath it - I really don't understand why that is included. It is orthogonal & serves only to waste scarce review time. Surely creating a branch and cherry-picking one patch is achievable ?

2024-11-13 14:22 UTC, mmeeks approved these changes

2024-11-13 17:57 UTC, merged