draft: refactor(clipboard): convert to async/await
CollaboraOnline/online pull request #10498
Opened 2024-11-14 16:27 UTC by Minion3665

Previously the read and write functions were using callbacks and promise
chains, which worked but would have been more annoying for me to extend
with android-specific clipboard things.

As a bonus, async/await reduces nesting and jumping around in the code,
which should also make this easier to read, and arrow functions remove
this->that aliasing

Finally, using async/await in new places allows us to better use
existing places which do provide promises, for example we can go back to
only fetching the clipboard a single time without re-introducing the
race condition which fetching twice solved

2024-11-15 04:09 UTC, eszkadev commented on browser/src/map/Clipboard.js
> +	}
missing `,`

2024-11-15 04:51 UTC, eszkadev commented
thanks, now looking per commit is much easier :)

2024-11-15 13:55 UTC, Minion3665 commented on browser/src/map/Clipboard.js
> +		var request = new XMLHttpRequest();
See conversation in #10484

2024-11-15 15:06 UTC, eszkadev commented
@Minion3665 it that PR for review and merge?

2024-11-15 15:07 UTC, Minion3665 commented
> @Minion3665 it that PR for review and merge?

yes please, I was just waiting to see that CI passed first

2024-11-18 10:26 UTC, eszkadev requested changes
it triggers for me in the debugger:
`_sendCommandAndWaitForCompletion was called with 'null', but anything except Copy or Cut will never complete`
when copying with keyboard shortcut in Calc in Chrome, selected: pause on unhandled exceptions

2024-11-18 10:27 UTC, Minion3665 commented
> it triggers for me in the debugger: `_sendCommandAndWaitForCompletion was called with 'null', but anything except Copy or Cut will never complete` when copying with keyboard shortcut in Calc in Chrome, selected: pause on unhandled exceptions

I think we need to rebase on something that has https://github.com/CollaboraOnline/online/pull/10506 to fix this

2024-11-18 11:05 UTC, eszkadev approved these changes
thanks, now it is fixed

2024-11-18 11:05 UTC, merged