Fix : Notebookbar Labels Decrease font size
CollaboraOnline/online pull request #2037
Opened 2021-04-17 14:53 UTC by codewithvk

Signed-off-by: codewithvk <vivekpatel7202@gmail.com>
Change-Id: I151db6e80a446eefdee21b5536e00694b9734074

* Resolves: #2002 
* Target version: master 

### Summary
![temp](https://user-images.githubusercontent.com/61119120/115117139-bb4c3800-9fba-11eb-9481-6c19f6ab070b.png)

2021-04-18 09:51 UTC, gokaysatir commented
Hello, Thank you for the patch:)

@pedropintosilva i think your opinion is more important then mine here:)

2021-04-19 11:54 UTC, pedropintosilva requested changes
Thanks for your patch! But unfortunately this does not affect those labels (it only affects nested widgets , `ui-widget .ui-widget`). Could you please change it? See my comments.

also 0.5em is extremely small, please make sure you able to run Collabora Online and test it, let me know if there is something I can help with : )

2021-04-19 11:57 UTC, pedropintosilva commented on loleaflet/css/jquery-ui-lightness.css
>  }
not the elements we are trying to target. Maybe they can then be removed (if they are not used anywhere else but for now and to make the things simple I would avoid changing this)

2021-04-19 11:59 UTC, pedropintosilva commented on loleaflet/css/jquery-ui-lightness.css
>  	font-size: 1.1em;
property of the intended element we are trying to target, maybe change it to 1em?

2021-04-19 13:22 UTC, codewithvk reviewed
Hey, I think this property not for our target, because it changes only hover text size.
![temp](https://user-images.githubusercontent.com/61119120/115243018-152a3a80-a140-11eb-94af-094c37e3e145.png)
Can you please confirm me?

2021-04-19 13:32 UTC, pedropintosilva commented
> Hey, I think this property not for our target, because it changes only hover text size.

Hm n0o, `.ui-widget, [data-title]:after` is what we want see:
![image](https://user-images.githubusercontent.com/65948705/115244377-2c5b2f00-a124-11eb-9d71-4a9d49ca5417.png)

2021-04-21 08:06 UTC, pedropintosilva approved these changes

2021-04-21 08:07 UTC, pedropintosilva commented
Thanks! We are currently having troubles with tests but I think we can just merge this : ) :+1:

2021-04-21 08:07 UTC, merged

2021-04-21 10:50 UTC, codewithvk commented
@pedropintosilva  Thanks for merge! This is my first contribution to CollaboraOnline project.
Looking forward more contribution :)

2021-04-21 11:52 UTC, pedropintosilva commented
I'm glad I could merge your very first PR. We also have also many [easyhacks](https://github.com/CollaboraOnline/online/issues?q=is%3Aissue+is%3Aopen+label%3A%22Easy+Hack%22) and many other [issues](https://github.com/CollaboraOnline/online/issues) to play with : ) ping me by @ me or chatting in our IRC: irc://irc.freenode.net/#cool-dev

2021-04-21 12:09 UTC, pedropintosilva commented
or on telegram if you prefer, all links listed in: https://collaboraonline.github.io/post/communicate/

2021-04-21 12:18 UTC, codewithvk commented
hey @pedropintosilva ,
when I had to press join button telegram to show me this
![temp](https://user-images.githubusercontent.com/61119120/115552230-b55f9b00-a2c9-11eb-9bf4-bd536368fc7d.png)