- Remove the unnecessary span because   - it can required further unnecessary styling   - Doe not add any semantic to the existent button element   - it can lead to different rendering depending on the 	device/browser combo
CollaboraOnline/online pull request #2974
Opened 2021-07-27 13:48 UTC by pedropintosilva

Signed-off-by: Pedro Pinto Silva <pedro.silva@collabora.com>
Change-Id: I88f1b97939c59927686bd72ea295f87abffcbe29

2021-07-27 14:13 UTC, eszkadev requested changes

2021-07-27 14:13 UTC, eszkadev commented on loleaflet/src/control/Control.JSDialogBuilder.js
>  			image.src = data.image;
this image inserted into pushbutton will be overwritten by innerHTML call later I think

2021-07-27 14:14 UTC, eszkadev commented on loleaflet/src/control/Control.JSDialogBuilder.js
>  			image.src = data.image;
also please check if sidebar popups which have buttons with images are correctly shown

2021-08-24 10:01 UTC, pedropintosilva commented
@Rash419 could you please take it over?

- I have fixed https://github.com/CollaboraOnline/online/issues/2812
- But now we need to make sure that we account for the cases Szymon described above

2021-08-24 11:15 UTC, Rash419 commented
> @Rash419 could you please take it over?
> 
> * I have fixed [Mobile: do not use span inside of a button element #2812](https://github.com/CollaboraOnline/online/issues/2812)
> * But now we need to make sure that we account for the cases Szymon described above
> 
> feel free to add commits to this PR

Yes syzmon is right if there will a button with image and text both the image will be replaced with text but I could find any instance where both is there in button @pedropintosilva

2021-09-13 08:37 UTC, eszkadev approved these changes
looks good

2021-09-13 08:37 UTC, merged