Make coolwsd-generate-proof-key prepared for a custom prefix.
CollaboraOnline/online pull request #3759
Opened 2021-11-30 16:13 UTC by arrowd

The downstream packagers can patch the "PREFIX=/" line to their liking.

While there, converts tabs into spaces for consistency.

Signed-off-by: Gleb Popov <6yearold@gmail.com>
Change-Id: I424f6fe6efac8e51f74f5848586e7fd10fa40904

2021-12-06 07:33 UTC, arrowd commented
Bump.

2021-12-07 07:34 UTC, vmiklos commented
@timar or @mikekaganski might be capable of reviewing this.

2021-12-07 07:37 UTC, mikekaganski commented
Mostly @timar - I am afraid I am not very familiar with *nix file storage conventions and jails ... sorry :-) - but looks perfectly reasonable from my PoV.

2021-12-07 12:54 UTC, timar requested changes
I do not want to nitpick a lot, and this patch is basically indifferent to Collabora's packages, but to generalize the location, would you consider using @LOOLWSD_CONFIGDIR@ and convert coolwsd-generate-proof-key to coolwsd-generate-proof-key.in so this location can be decided build-time?

2021-12-08 06:37 UTC, arrowd commented
> I do not want to nitpick a lot, and this patch is basically indifferent to Collabora's packages, but to generalize the location, would you consider using @LOOLWSD_CONFIGDIR@ and convert coolwsd-generate-proof-key to coolwsd-generate-proof-key.in so this location can be decided build-time?

This is a nice suggestion. But I also have one - how about just passing the path to the config as the script parameter?

If there are no args the script would use `/etc/coolwsd` and otherwise use `$1`?

2021-12-08 07:52 UTC, timar commented
> > I do not want to nitpick a lot, and this patch is basically indifferent to Collabora's packages, but to generalize the location, would you consider using @LOOLWSD_CONFIGDIR@ and convert coolwsd-generate-proof-key to coolwsd-generate-proof-key.in so this location can be decided build-time?
> 
> This is a nice suggestion. But I also have one - how about just passing the path to the config as the script parameter?
> 
> If there are no args the script would use `/etc/coolwsd` and otherwise use `$1`?

OK!

2021-12-16 09:31 UTC, arrowd commented
Bump.

2021-12-21 12:27 UTC, arrowd commented
Another bump.

2021-12-22 14:18 UTC, timar approved these changes

2021-12-22 14:18 UTC, merged