Cool Header with filename and save date depend on window width
CollaboraOnline/online pull request #3839
Opened 2021-12-09 23:26 UTC by Andreas-Kainz

** background color **
Remove background color for each single header element, so it's
possible to switch the global header color easy

** align header text **
The header elements are vertical center align

** resize window **
the filename was shown depend on the window with
the save date was shown depend on the window with
first the filename was hidden.

Signed-off-by: andreas kainz <kainz.a@gmail.com>
Change-Id: I9e275ab7105ace8147f3d07ca73a59a3818dbc29

* Resolves: #3829
* Target version: master

2021-12-17 11:08 UTC, pedropintosilva requested changes
Thanks @Andreas-Kainz I will check it locally, but at the first sight do you think we could convert all or any of those rules that are inside of media queries into normal rules inside of `browser/css/device-tablet.css` or `browser/css/device-mobile.css`

device-xxx.css is conditionally loaded depending on each case (as you can see in https://github.com/CollaboraOnline/online/blob/master/browser/html/cool.html.m4#L346 )

2021-12-17 11:38 UTC, pedropintosilva commented
and it seems something affected the tabs, see the cropped one:
![image](https://user-images.githubusercontent.com/65948705/146538963-ff06f48c-8042-4aaf-95d4-c360cf0691f7.png)

2021-12-17 14:57 UTC, Andreas-Kainz commented
I want to make first classic toolbar and after that tabbed one. But however I can add tabbed to.

I understood that you want to have clear decisions communicated at the git history. I myself I'm fit simple and small patches for example.

2021-12-19 22:03 UTC, Andreas-Kainz commented
> and it seems something affected the tabs, see the cropped one: ![image](https://user-images.githubusercontent.com/65948705/146538963-ff06f48c-8042-4aaf-95d4-c360cf0691f7.png)

fixed

2021-12-19 22:35 UTC, Andreas-Kainz commented
![Screenshot_20211219_233447](https://user-images.githubusercontent.com/8517736/146693332-9be82799-acf0-427c-bdb1-e93cbdc23ab3.png)
now resizing work at standard toolbar AND notebookbar.

2022-01-04 09:59 UTC, Andreas-Kainz commented
@pedropintosilva review and feedback would be awesome.

2022-01-10 15:40 UTC, pedropintosilva requested changes

2022-01-10 15:40 UTC, pedropintosilva commented on browser/css/menubar.css
> +	background: transparent;
I have created a PR with a commit just for the colours, maybe we can divide further this PR into several commits, I will help you with that.

2022-01-10 15:40 UTC, pedropintosilva commented on browser/css/menubar.css
> +	height: 36px; /* on mouseover menubar items, border emerges */
I think this is not needed 5 days ago on of my PRs from Nov. got merged that modifies this: (more info: https://github.com/CollaboraOnline/online/pull/3713)

2022-01-10 15:40 UTC, pedropintosilva commented on browser/css/menubar.css
> +	align-items: center;
Vertical align nav bar and its child: maybe better to have a commit only fr this

2022-01-10 15:40 UTC, pedropintosilva commented on browser/css/menubar.css
> +}
Part of Vertical align nav bar and its child: no need to specifically target classic menu since #main-menu is only visible when using classic mode

2022-01-10 15:40 UTC, pedropintosilva commented on browser/css/menubar.css
> +
These media queries, some maybe can be in some of the device specific CSS files we have others probably not specially if we want it to react to window resize but then we should test these first in a real tablet (not the responsive mode that can sometimes be tricky) to see if it affects it or not

2022-01-10 15:40 UTC, pedropintosilva commented on browser/css/menubar.css
> +	background: transparent;
https://github.com/CollaboraOnline/online/pull/3906

2022-01-10 15:41 UTC, pedropintosilva commented on browser/css/menubar.css
> +	align-items: center;
_cherry-picking and creating a new commit just with your Vertical align nav bar changes_

2022-01-10 15:51 UTC, pedropintosilva commented on browser/css/menubar.css
> +	align-items: center;
Tested and the lack of padding made it look very cramped up (without enough white space around), pick everything else though: https://github.com/CollaboraOnline/online/pull/3952

2022-01-10 16:28 UTC, Andreas-Kainz commented
@pedropintosilva can you please fix the conflict.

2022-01-12 21:41 UTC, Andreas-Kainz commented
the change was a backport of what nextcloud office did. So I don't know what each single change did, cause the change come from nextcloud office.

2022-01-23 21:04 UTC, closed without merging