browser: add file path tooltip
CollaboraOnline/online pull request #3881
Opened 2021-12-20 06:32 UTC by alessioalex-1and1

Signed-off-by: Alexandru Vlăduţu <alexandru.vladutu@1and1.ro>
Change-Id: Ie163ee479ee62d314248a8b891751a3755eca4ca

* Resolves: #3880
* Target version: master 

### Summary

Adds the file path as a title attribute so that it shows up as a tooltip when you mouse over the file name. It show up as the following:

```
File_name.extension
Path: Path/to/folder/containing/file
```

Added the translation for the most popular languages for 'Path': English, French, Spanish, Italian (bonus: Romanian).

### TODO

- [ ] ...

### Checklist

- [x] Code is properly formatted
- [x] All commits have Change-Id
- [ ] I have run tests with `make check`
- [x] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

2022-01-03 11:20 UTC, pedropintosilva approved these changes
Thanks @alessioalex-1and1 ! it works : )

2022-01-03 11:21 UTC, pedropintosilva commented
weird it seems there was a http problem on the GitHub side could you please rebase and retrigger it ?

2022-01-11 08:22 UTC, alessioalex-1and1 commented
@pedropintosilva made another push

2022-01-11 16:38 UTC, pedropintosilva commented
thanks @alessioalex-1and1 but I see that the latest changes are not yet in your branch could you please rebase it and then push? 

1. git checkout master
2. (make sure you have no new changes or new commits in your master branch and then) git pull -r
3. git checkout filepath-tooltip 
4. git rebase master
5. and then finally force push as you did it already

2022-01-11 16:45 UTC, pedropintosilva commented
nevermind I just added your forked repo as an additional remote and rebased + forced pushed for you : )

2022-01-12 06:43 UTC, timar requested changes
You cannot use l10n/uno files for localization of 'Path'. Those files will be overwritten when we update uno command translations from core next time. Normal l10n process will take care of it (Po files/Weblate).

2022-01-12 08:31 UTC, pedropintosilva commented
@alessioalex-1and1 ^ sorry I forgot to tell you bout that (Thanks @timar for the heads up) So I think you can amend your commit and remove the changes from all those l10n (json) files and keep only the JS change. We can then proceed with adding these new strings in the [weblate](https://hosted.weblate.org/projects/collabora-online/ui/) itself (and benefit from the Glossary and other functionalities in there)

2022-01-12 11:10 UTC, alessioalex-1and1 commented
@pedropintosilva I did what you asked in your previous comment. Can I add the translations to 'Path' to weblate myself? Are there any quick tips on how to do that? Thanks!

2022-01-12 13:39 UTC, pedropintosilva approved these changes

2022-01-13 11:14 UTC, timar approved these changes

2022-01-13 11:14 UTC, merged