writer notebookbar stylesview previews no padding
CollaboraOnline/online pull request #4616
Opened 2022-04-15 22:46 UTC by Andreas-Kainz

remove padding-top: 5px so there is no scrolling
needed for two rows.

![image](https://user-images.githubusercontent.com/8517736/163650333-2139e9da-825e-41e7-a951-27fe5982b347.png)

Signed-off-by: andreas kainz <kainz.a@gmail.com>
Change-Id: I9a0450074cc55486d0f7de8a39b7edff8e66c752

2022-04-18 08:18 UTC, pedropintosilva requested changes
Thanks! Removing the top padding decreases the need for scroll (even thought we will always have scroll if the document has more styles than the hello-world.odt) but this is also a good improvement in terms of alignment :+1: 

Just one note: Wouldn't be better to instead of adding a padding-top 0 have this removed https://github.com/CollaboraOnline/online/blob/master/browser/css/jsdialogs.css#L521 ? I think it affects other places where we use the icon view (fontwork)

2022-04-20 07:56 UTC, Andreas-Kainz commented
Thanks for the feedback. Remove padding-top from jsdialogs.css didn't work well. There is a padding around all fontwork elements. 

So no only .stylesview need `padding-top: 0px;` as defined in the PR.

2022-04-22 06:34 UTC, Andreas-Kainz commented
@pedropintosilva do I have to rebase the PR. I don't think that my PR is the issue of the Test.

2022-04-26 05:22 UTC, pedropintosilva commented
something happened because your PR has 28 commits

2022-04-26 05:22 UTC, pedropintosilva commented
we need only your commits

2022-04-26 05:22 UTC, pedropintosilva commented
let me fix that for you

2022-05-01 19:08 UTC, Andreas-Kainz commented
I think it can go to master @pedropintosilva

2022-05-03 07:58 UTC, pedropintosilva approved these changes
approved, Thanks for checking it out the possibilities here.

2022-05-03 07:58 UTC, merged