Sidebar alignment commands main sections
CollaboraOnline/online pull request #4621
Opened 2022-04-17 21:07 UTC by Andreas-Kainz

the sidebar alignments didn't work again
this will simplyfy the global .sidebar.ui-exmander
and the .sidebar.ui-expander-content

Now there will be left and right 8px padding
and the ui-expander use 100%. So everything
will be mirrored.

Signed-off-by: andreas kainz <kainz.a@gmail.com>
Change-Id: I4a8f94ffd404501dbb24b458f1210066769b9897

2022-04-17 21:07 UTC, Andreas-Kainz commented
fix is very generic. next PR's are for the separate .ui-expander sections

2022-04-18 10:15 UTC, pedropintosilva requested changes
* Please use CSS logic properties so it does not break for RTL (for padding and margin)
* Also worth look into @eszkadev changes already merged from https://github.com/CollaboraOnline/online/pull/4571 

Ideally I would like to have any margin or padding merged form multiple containers (e.g `.jsdialog.root-container`) and have just one `width: calc(100% - 16px);`  possible combined with margin-inline-start (we currently have multiple)

2022-04-19 13:36 UTC, pedropintosilva commented
I meant logic not login :facepalm:

2022-04-20 08:19 UTC, Andreas-Kainz commented
I will investigate farther and update the PR. Main purpose is cleanup, simplify and RTL.

2022-04-26 06:23 UTC, pedropintosilva commented
more info at https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties

2022-05-18 06:41 UTC, closed without merging

2022-05-18 06:41 UTC, Andreas-Kainz commented
work is done at #4776