Expose object name and description dialogs
CollaboraOnline/online pull request #4765
Opened 2022-05-12 08:13 UTC by NickWingate

Signed-off-by: NickWingate <nick.wingate@collabora.com>
Change-Id: Ica06259dc3007d638a4998ccc2cce03ad1a5ca05

* Resolves: # 
* Target version: master 

### Summary

### TODO

- [ ] Get working in core https://gerrit.libreoffice.org/c/core/+/133435

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

2024-03-14 10:17 UTC, mmeeks commented
@eszkadev  can we review this and/or find someone to take over the draft and merge it ? =)

2024-03-27 11:41 UTC, eszkadev requested changes
It exposes tunneled dialogs, have to be enabled in the core first.

"Name" dialogs allow to name objects so we can identify them in the navigator - very useful.
"Description" - setups invisible description property? I don't see why it is needed.

2024-03-27 11:42 UTC, eszkadev commented
if 2 icons are the same but have different name in the code - please use alias to not use additional space. It can be done in Control.JSDialogBuilder.js - find long list of strings mapped to other strings.

2024-05-07 20:01 UTC, eszkadev approved these changes

2024-05-09 06:47 UTC, merged