Compact View isn't part of Sidebar, Statusbar
CollaboraOnline/online pull request #4782
Opened 2022-05-17 23:11 UTC by Andreas-Kainz

Compact View is separate in the menubar from Sidebar and Statusbar
So it shouldn't be between them in the View Tab.

![image](https://user-images.githubusercontent.com/8517736/168926837-3d6fdf1e-596f-4c45-a25e-d6f8975e8f6c.png)

Signed-off-by: andreas kainz <kainz.a@gmail.com>
Change-Id: Ib46e9c4a4df24432eae5a7fef335e7cde68b1766

2022-05-17 23:12 UTC, Andreas-Kainz commented
If you think it's only a Change cause of a change, I can close the PR.

From my point of view Compact view shouldn't be between Sidebar and Statusbar. It should be the first item or the last one in this "group".

2022-05-23 11:02 UTC, pedropintosilva requested changes
Thanks @Andreas-Kainz for looking at this. I think we can improve here. Even thought the top menus on the compact view don't need to be 1 to 1 with tabbed view tabs (sometimes they really shouldn't) in this case I would say you are right. Nevertheless I would prefer to have the view button to the the first and the sidebar the last because:
1. Then the Sidebar icon is the rightmost icon which is nice since the sidebar comes from that sode
2. The view button would be in the leftmost side from those icons. That's ideal since it's an action that is not only hierarchy above the other actions in that group of buttons but also probably more important to the user to spot straight away 

TLDR: 
![image](https://user-images.githubusercontent.com/65948705/169805439-b94bb31f-82e4-4fbf-9495-19f40fc09865.png)

2022-05-23 11:05 UTC, Andreas-Kainz commented
Thank's for the feedback I also didn't know what first, so I make one variant and get now your feedback. 

Will update the PR.

2022-05-23 11:13 UTC, pedropintosilva commented
no sweat : ) and thanks for improving this up ;)

2022-05-23 22:43 UTC, Andreas-Kainz commented
I will make the showstatusbar from menubartoolitem to a bigmenubartoolitem I think you already did it @pedropintosilva do you have a PR example?

2022-05-26 11:02 UTC, pedropintosilva requested changes
Something odd in impress:
![image](https://user-images.githubusercontent.com/65948705/170475459-60351e27-e683-47cf-b803-afa18dda55df.png)

2022-06-01 21:24 UTC, Andreas-Kainz commented
> Something odd in impress: ![image](https://user-images.githubusercontent.com/65948705/170475459-60351e27-e683-47cf-b803-afa18dda55df.png)

you mean cause Status Bar isn't a bigtoolitem? That's the same within master. Open an issue. I don't want to fix it with this PR cause I don't want to mix different stuff.

2022-06-02 09:28 UTC, pedropintosilva commented
> you mean cause Status Bar isn't a bigtoolitem?

No, because of this you have added other icons to the view tab, in Impress

2022-06-09 09:58 UTC, merged