indirect logo
CollaboraOnline/online pull request #4843
Opened 2022-06-02 01:36 UTC by hcvcastro

- wsd: add indirect request logo image
- browser: css: add '#lokit-logo' style to fetch logo.png
- wsd: cache logo image

* Resolves: # 
* Target version: master 

### Summary

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

2022-06-02 05:44 UTC, timar requested changes

2022-06-02 05:44 UTC, timar commented on browser/css/cool.css
> +
it's defined in branding.css

2022-06-02 05:44 UTC, timar commented on wsd/FileServer.cpp
> +#define DEFAULT_LOGO "https://www.libreoffice.org/themes/libreofficenew/img/logo.png"
wrong logo

2022-06-02 08:22 UTC, mmeeks requested changes
Some tweaks needed here.

2022-06-03 15:50 UTC, hcvcastro commented
Changes done

2022-06-03 16:11 UTC, mmeeks approved these changes
Much better - if Ash is happy with the indirect thing which (I'd like to hope) is not necessary - then this looks good to me.

2022-06-06 15:22 UTC, hcvcastro commented
Updated changes

2022-06-07 08:19 UTC, mmeeks reviewed
Nearly there ! =) a few comments, I guess Ash may have some more. Thanks for getting this over the line Henry !

2022-06-07 08:19 UTC, mmeeks commented on wsd/COOLWSD.cpp
> -    WebServerPoll = Util::make_unique<TerminatingPoll>("websrv_poll");
Not so sure on this one - one of the things I like from a security perspective is having loaded all the files from the file-system, and having cached them internally before we start our various other polls on listening sockets and accept external messages.
Perhaps we should have a large comment // ---------------- from here on we start getting external messages ----------------
in there in the original place.
If we need to have another part of this doing later can we have it in a method after webserver init etc. which should happen after the fileserver setup.

2022-06-07 08:19 UTC, mmeeks commented on wsd/FileServer.cpp
> +        if (Util::startsWith(relPath, std::string("/browser/dist/remote/logo.svg")))
I'd really prefer the same name lokit-extra-img.svg as we pass it through - renaming things as they go past makes things more complex to maintain I think.

2022-06-07 13:43 UTC, hcvcastro commented
Updated changes

2022-06-07 13:54 UTC, mmeeks reviewed
Looks great to me - if Ash is happy with the socket/request stuff I'd love to get it in =)

2022-06-07 14:42 UTC, mmeeks commented
Ash says: " yes, looks good. " =) thanks Henry.

2022-06-07 14:42 UTC, merged

2022-06-07 16:26 UTC, hcvcastro commented
/backport to distro/collabora/co-21-11

2022-06-08 01:48 UTC, Ashod commented
Thanks @hcvcastro, good stuff!