Revise dark variant of Picture Control icon
CollaboraOnline/online pull request #4926
Opened 2022-06-18 13:41 UTC by rizmut

Signed-off-by: Rizal Muttaqin <riz_17_oke@yahoo.co.id>
Change-Id: I728152c67975fd297b2035d4bf102cc5c57695f1

* Resolves: #4845
* Target version: master 

### Summary

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

2022-06-20 14:41 UTC, pedropintosilva requested changes

2022-06-20 21:58 UTC, rizmut commented on browser/images/dark/lc_insertpicturecontentcontrol.svg
> +<svg height="24" viewBox="0 0 6.3499998 6.3499998" width="24" xmlns="http://www.w3.org/2000/svg"><g transform="translate(0 -290.65)"><path d="m2.6458334 294.08958-1.8520834 1.85209v.26458h.13229167l1
I never dig down to the source of SVG file. What I've been doing so far is drawing using Inkscape then reducing the size with rsvg

2022-06-30 09:42 UTC, pedropintosilva commented on browser/images/dark/lc_insertpicturecontentcontrol.svg
> +<svg height="24" viewBox="0 0 6.3499998 6.3499998" width="24" xmlns="http://www.w3.org/2000/svg"><g transform="translate(0 -290.65)"><path d="m2.6458334 294.08958-1.8520834 1.85209v.26458h.13229167l1
hm, I have tested and it works, but it seems something went wrong while Inkscape saved it, or maybe while editing it. Maybe better to save it as plain svg or inspect what is going on with the Inkscape's XML editor. But for now I will merge this thanks! Please feel free to push another PR if you end up tweaking or find ways to improve this ;)

2022-06-30 09:43 UTC, pedropintosilva approved these changes

2022-06-30 09:43 UTC, merged