replaced magic numbers :D
CollaboraOnline/online pull request #4961
Opened 2022-06-28 18:37 UTC by Rimuruweeb

* Resolves: # 
* Target version: master 

### Summary
on line 603 couldn't replace 99 , idk was giving some error , i checked every number tho :P.

2022-06-29 09:48 UTC, Rash419 commented
@Rimuruweeb thanks for the PR 
DCO and Change-Id checks are failing if you click on the details you will find out what is the problem 
commit message should be meaningfull 
checkout this guide for more info: https://www.freecodecamp.org/news/writing-good-commit-messages-a-practical-guide/

2022-06-29 13:14 UTC, pedropintosilva commented
Thanks and welcome @Rimuruweeb ! As @Rash419 already pointed out you need to:

2022-07-05 15:08 UTC, Rimuruweeb commented on browser/src/map/handler/Map.Keyboard.js
> +		pageUp:   UNOKey.PAGEUP,
Do you want me to revert backchanges in keycodes ? and everything expect keycodes are alright?

2022-07-05 15:15 UTC, Rimuruweeb commented on browser/src/map/handler/Map.Keyboard.js
> +		pageUp:   UNOKey.PAGEUP,
i mean your example gave this values  112 to UNOKey.F1.

2022-07-06 12:44 UTC, Rimuruweeb commented on browser/src/map/handler/Map.Keyboard.js
> +		pageUp:   UNOKey.PAGEUP,
sir thank you for your response but it says keycodes are not defined,
![image](https://user-images.githubusercontent.com/85924406/177552917-daa2b92e-9f1d-466c-8b44-e6e422b81931.png)

2022-07-06 12:57 UTC, pedropintosilva commented on browser/src/map/handler/Map.Keyboard.js
> +		pageUp:   UNOKey.PAGEUP,
@Rimuruweeb it is defined in https://github.com/CollaboraOnline/online/blob/master/browser/src/map/handler/Map.Keyboard.js#L320 
```js
var keyCode = ev.keyCode;
```

2022-07-06 13:03 UTC, Rimuruweeb commented on browser/src/map/handler/Map.Keyboard.js
> +		pageUp:   UNOKey.PAGEUP,
i think sir @eszkadev meant keyCodes not keyCode .

2022-07-06 13:03 UTC, eszkadev commented on browser/src/map/handler/Map.Keyboard.js
> +		pageUp:   UNOKey.PAGEUP,
@pedropintosilva no it is not what we want here

2022-07-06 13:04 UTC, eszkadev commented on browser/src/map/handler/Map.Keyboard.js
> +		pageUp:   UNOKey.PAGEUP,
@Rimuruweeb you need to add new names/memebers into that dictionary we are commenting right now.

https://github.com/CollaboraOnline/online/pull/4961/files/4be9181d18921604e4abcffba6f70472af52cc82#diff-5c4df738e4e71c87f575a954037607d6ffac23b63686d7de65dd029bca95eed6L142

that is good place where we can define buinding between   name  and number value

2022-07-06 13:48 UTC, eszkadev commented on browser/src/map/handler/Map.Keyboard.js
> +		pageUp:   UNOKey.PAGEUP,
> @eszkadev you want me to add name and numbers to this scope?
> 
> https://github.com/CollaboraOnline/online/blob/4be9181d18921604e4abcffba6f70472af52cc82/browser/src/map/handler/Map.Keyboard.js#L142

Yes

2022-07-06 15:10 UTC, eszkadev requested changes

2022-07-06 15:10 UTC, eszkadev commented on browser/src/map/handler/Map.Keyboard.js
> +		113 : true  // f2sss
this is probably mistake :) please revet this change

2022-07-06 15:10 UTC, eszkadev commented on browser/src/map/handler/Map.Keyboard.js
> +		BACKSPACE   : UNOKey.BACKSPACE,
Please DO NOT USE `UNOKey` enum here. I said it was misleading comment from my side to show that dictionary as an example.

What we want here is to bind NAME with NUMBER. `pageUp: 33` and others should stay here, they are correct bindings. Please only add new ones for missing keyCodes used in this file.

like on the bottom we have `45`, you should add here: `INSERT: 45,`, then replace occurrences of `45` with `this.keyCodes.INSERT`  - this is done great already :)

2022-07-06 15:11 UTC, eszkadev commented on browser/src/map/handler/Map.Keyboard.js
> +		BACKSPACE   : UNOKey.BACKSPACE,
( `UNOKey` stores values like `1034` which are different than keyCodes used by the browser, `UNOKey` enum is for our server which uses different coding )

2022-07-11 10:11 UTC, eszkadev commented
> Hello, is this PR fine now? Can we rebase and review again? Looks like a good improvement :)

No, it uses incorrect values currently.

2022-10-14 09:12 UTC, eszkadev commented
Issue fixed with other commit.

2022-10-14 09:12 UTC, closed without merging