sidebar: show Misc panel with Table Cell Color
CollaboraOnline/online pull request #5074
Opened 2022-07-28 09:32 UTC by eszkadev

It was removed in:
mobile wizard: hide unsupported items in table panel
commit 1aed5ddaa440c0d687708bd0ba7819499dd247fc

but now works

related to: https://github.com/CollaboraOnline/online/issues/4942

2022-07-28 09:37 UTC, pedropintosilva commented
note: why no border style? ->  border style popup doesn't work yet (app hangs, cannot close)

2022-07-29 07:42 UTC, pedropintosilva requested changes
It works as expected, Thanks!  Could you please rebase without the additional SVG? Probably best to just re-use `lc_fillcolor.svg` by adding `'tablecellbackgroundcolor': 'fillcolor',` to iconURLAliases in Control.JSDialogBuilder.js

2022-07-29 09:12 UTC, eszkadev commented
@pedropintosilva rebase done

2022-08-04 11:16 UTC, pedropintosilva approved these changes
Thanks!

2022-08-04 11:17 UTC, merged