DeepL translation integration
CollaboraOnline/online pull request #5096
Opened 2022-08-03 11:43 UTC by merttumer

this patch relies on a core change:
https://gerrit.libreoffice.org/c/core/+/137199

Signed-off-by: Mert Tumer <mert.tumer@collabora.com>
Change-Id: Ie5f5dada18539586e7c5ea41b0a296b33ae8ee2e

* Resolves: # 
* Target version: master 

### Summary

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

2022-08-03 11:48 UTC, merttumer commented
@pedropintosilva we need a new icon for uno:Translate

2022-08-03 15:35 UTC, pedropintosilva commented
I tried to create an icon reminiscent from the existent colibre theme language (used in review tab)

I also wonder why we are using the new translate btn in format instead of placing it in the Review tab

2022-08-04 07:16 UTC, pedropintosilva requested changes

2022-08-04 07:16 UTC, pedropintosilva commented on browser/src/control/Control.NotebookbarWriter.js
> +			{
Could you please move this into `getReviewTab`, after `LanguageMenu`

2022-08-25 12:28 UTC, pedropintosilva approved these changes

2022-08-25 12:28 UTC, merged