Add outline to color indicator for classic mode
CollaboraOnline/online pull request #5135
Opened 2022-08-10 14:29 UTC by bayramcicek

- In classic mode, toolbar color indicators weren't visible when no
  text is selected. The reason is that color indicators didn't have
  border(outline) color.
- In fact, color indicators were just a box-shadow property. So,
  it was not possible(?) to add properties like border and
  border-radius.
- No need to use box-shadow property. A `<div>` tag can represent
  color indicators.
- Removed box-shadow property.
- Added `<div>` tag that has `class="selected-color-classic"`.

Signed-off-by: Bayram Çiçek <bayram.cicek@libreoffice.org>
Change-Id: I1b1b68fdc015fd3719d1c59ef7f782036a5934a5

* Resolves: #2809
* Target version: master 

### Summary

- Outline/border added to color indicator by creating `<div>` element.
- This commit only resolves outline/border issue in classic mode.

### Other issues

In classic mode: 
- [ ] Changes in toolbar's font&highlighting color, doesn't change the sidebar's font&highlighting color.
- [ ] In toolbar, selecting the same color, resets the color indicator to white.
- [ ] In Calc's toolbar, there is no icon/image for Background Color (`class="backgroundcolor"`).
- [ ] In Draw's toolbar, font&highlighting color components doesn't work at all.

* Issues listed above still exist regardless of this patch. 

### Checklist

- [ ] Code is properly formatted
- [x] All commits have Change-Id
- [ ] I have run tests with `make check`
- [x] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

2022-08-11 17:13 UTC, eszkadev reviewed
It looks nice. @pedropintosilva if you are ok with it we can merge :)

2022-08-11 17:14 UTC, eszkadev commented
btw I've noticed in classic mode color picker still works like in the past (doesn't remember last used color but shows color of the currently selected text)

2022-08-12 13:46 UTC, pedropintosilva requested changes
Thanks @bayramcicek for this! It works as expected and if @eszkadev is ok with the w2ui file changes then I'm happy to merge this. The only thing I could point out is:

2022-08-12 13:46 UTC, pedropintosilva commented on browser/css/w2ui-1.5.rc1.css
> +  width: 24px;
Probably this should be 26px, so it is aligned to the top element (since the sibling has 24px width + 1 margin left +1 margin right = 26px)

2022-08-12 17:06 UTC, pedropintosilva approved these changes
Awesome, thanks!

2022-08-12 18:01 UTC, bayramcicek commented
Thanks to both of you for review! 
(BTW, I have no idea why one of the Cypress tests gives failure.)
(`make -C cypress_test check-mobile spec=writer/shape_properties_spec.js` <-- fails.)

2022-08-15 10:05 UTC, pedropintosilva commented
hm cypress is not passing on CI, I also tested locally and I confirm the test didn;t pass

2022-08-15 10:05 UTC, pedropintosilva commented
I'm now rebasing this branch locally with master to see if there is nay difference in the cypress outcomes

2022-08-15 10:54 UTC, pedropintosilva requested changes
There is one more thing needed before we can merge this. Dimensions on mobile are being affected by this. You can see the cypress running by ``


This happens because we now have two elements that are occupying more height than expected: ![image](https://user-images.githubusercontent.com/65948705/184622271-a26ab8a5-4bf3-4ba9-bbb5-e16a6bc12a67.png) Plus there misalignment going now there.

Could you please:
- Make sure we use `margin:auto` for `.selected-color-classic` when on mobile #toolbar-down
- Set `.selected-color-classic` with smaller height on mobile e.g.: height: 5px;
- Also set `#toolbar-down table.w2ui-button .w2ui-tb-image` element (inside  `#tb_editbar_item_backcolor` and `#tb_editbar_item_fontcolor`) with `0` bottom margin

2022-08-16 07:14 UTC, pedropintosilva requested changes
Thanks! It now passes all tests, and it works both on mobile and desktop :partying_face: . There are just 2 details that could be improved, sorry for nitpicking here.

2022-08-16 07:14 UTC, pedropintosilva commented on browser/css/device-mobile.css
> +}
I have tested and as far as I can see we don't use `.backgroundcolor` on mobile #toolbar-down so this can be removed

2022-08-16 07:14 UTC, pedropintosilva commented on browser/css/device-mobile.css
> +	margin: 5px 9px 0px !important;
maybe better to use `margin-bottom` instead, so to avoid duplications since we can inherit the rest

2022-08-16 13:48 UTC, pedropintosilva approved these changes
Thanks!

2022-08-16 13:49 UTC, merged