feat(toolbar): add background, center align elements & remove checkmark
CollaboraOnline/online pull request #5489
Opened 2022-11-17 18:42 UTC by akshatakulkarni25

Signed-off-by: Akshata Kulkarni <akshatakulkarni2509@gmail.com>
Change-Id: Id44ba88a8645ff4bcb29cc645b180693c7dcece9

* Resolves: #  
* #2072 
* Target version: master 

### Summary
Resolves the issue by adding a conditional check for item that is selected and changing its background colour, text alignment and removes checked icon. 

### TODO

- [ ] ...

### Checklist

- [x] Code is properly formatted
- [x] All commits have Change-Id
- [x] I have run tests with `make check`
- [x] I have issued `make run` and manually verified that everything looks okay
- [x] Documentation (manuals or wiki) has been updated or is not required

<img width="1512" alt="Screenshot 2022-11-17 at 11 22 55 PM" src="https://user-images.githubusercontent.com/101616789/202531015-fb29bd95-6aaf-4b12-8859-53931f6e99cc.png">

2022-11-22 11:05 UTC, Rash419 commented
@akshatakulkarni25 Thanks for the PR , I will review it : )

2022-11-22 15:43 UTC, pedropintosilva requested changes

2022-11-22 15:43 UTC, pedropintosilva commented on browser/css/w2ui-1.5.rc1.css
> +  font-size: 16px;
Please these additional rules at the end of the `toolbar.css` file. This way we keep the original w2ui file clean and less prone to changes and use the later file to overwrite those rules.

Also maybe we could use CSS var for the font-size, you can add a new one (example `--toolbar-drop-menu-font-size`) in the top of `color-palette.css`

2022-11-22 15:43 UTC, pedropintosilva commented on browser/css/w2ui-1.5.rc1.css
> +}
Please add these at the end of  `toolbar.css` instead

2022-11-22 15:44 UTC, pedropintosilva commented on browser/css/w2ui-1.5.rc1.css
> +}
and consider using css var. maybe `--color-overlay` ?

2022-11-29 06:24 UTC, akshatakulkarni25 commented
@pedropintosilva I have completed the review changes please verify.

2022-12-05 16:48 UTC, pedropintosilva requested changes

2022-12-05 16:48 UTC, pedropintosilva commented on browser/css/toolbar.css
> +  	font-size: var(--toolbar-drop-menu-font-size);
Please remove the space before the tab in this line

2022-12-05 16:49 UTC, pedropintosilva commented on browser/css/toolbar.css
> +  	font-size: var(--toolbar-drop-menu-font-size);
I'm asking these because otherwise the lint test fails and it's impossible to build it

2022-12-05 17:01 UTC, pedropintosilva commented
Also, and after the about request is done would be nice to have your two commits in one, so to avoid having a "fix of a fix" in the git history. For these you need to squash the commits. For that you need to type in your terminal:

```bash
git rebase -i HEAD~2
```

Editor will open
```
pick e2ecaadaf feat(toolbar): add background, center align elements & remove checkmark
pick b61257b8c fix(code review): created css var for color overlay & toolbar dropdown font size
```

Change the first word of the last line to `squash`, save and close the text editor. A new text editor window will open with:

```
# This is a combination of 2 commits.
# This is the 1st commit message:

feat(toolbar): add background, center align elements & remove checkmark

Signed-off-by: Akshata Kulkarni <akshatakulkarni2509@gmail.com>
Change-Id: Id44ba88a8645ff4bcb29cc645b180693c7dcece9

# This is the commit message #2:

fix(code review): created css var for color overlay & toolbar dropdown font size

# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# Author:    Akshata Kulkarni <akshatakulkarni2509@gmail.com>
# Date:      Thu Nov 17 18:29:40 2022 +0000
#
# interactive rebase in progress; onto 510f5bb7a
# Last commands done (2 commands done):
#    pick e2ecaadaf feat(toolbar): add background, center align elements & remove checkmark
#    squash b61257b8c fix(code review): created css var for color overlay & toolbar dropdown font size
# No commands remaining.
# You are currently rebasing branch 'toolbar-style-change' on '510f5bb7a'.
#
# Changes to be committed:
#	modified:   browser/css/color-palette.css
#	modified:   browser/css/toolbar.css
#	modified:   browser/js/w2ui-1.5.rc1.js
#

```

edit that text and remove everything after the first commit message so, this would be the end result:
```
feat(toolbar): add background, center align elements & remove checkmark

Signed-off-by: Akshata Kulkarni <akshatakulkarni2509@gmail.com>
Change-Id: Id44ba88a8645ff4bcb29cc645b180693c7dcece9


```

2024-04-04 09:10 UTC, eszkadev requested changes
we are removing w2ui: https://github.com/CollaboraOnline/online/pull/8682
this will no longer not apply to the code, could you check the new PR, if it is fixed or needs something to do?

2024-05-30 09:06 UTC, closed without merging