introduce Zotero
CollaboraOnline/online pull request #5521
Opened 2022-11-26 10:05 UTC by lpranam

* Target version: master 

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

2022-11-27 21:27 UTC, timar commented on configure.ac
> +                             [Enable control over which uno-commands/feature to disable completely.]))
copy&paste error

2022-11-27 21:32 UTC, timar commented on common/Zotero.hpp
> +    static bool bla;
bla ?

2022-11-27 21:33 UTC, timar commented on common/Zotero.cpp
> +bool ZoteroConfig::bla = false;
bla ?

2022-11-27 21:55 UTC, timar requested changes
I'm not a big fan of the new configure option `--enable-zotero`, I think we should have it unconditionally. (But perhaps a second review on this would be the best.) It would be a lot of work to add the new configure option to every build script. 
On the other hand, I don't think we can have it mobile apps in the first round, unless it's straightforward. I think the same applies to DeepL and Languagetool integrations , too.

2022-11-28 10:36 UTC, lpranam commented on common/Zotero.hpp
> +    static bool bla;
lol sorry about it 😂

2022-11-28 12:16 UTC, timar commented on coolwsd.xml.in
> +        <enable dec="Enable Zotero plugin." type="bool" default="false">true</enable>
change default

2022-11-30 19:37 UTC, timar approved these changes

2022-11-30 19:37 UTC, merged

2022-11-30 20:50 UTC, Andreas-Kainz commented
I would prefer a more zotero styled icon (which I can make if you want).