icon size use css variables #5420
CollaboraOnline/online pull request #5561
Opened 2022-12-04 14:21 UTC by Andreas-Kainz

add variables to color-scheme.css file
replace hardcoded sizes with var's at
- notebookbar
- toolbar
- sidebar

Signed-off-by: andreas kainz <kainz.a@gmail.com>
Change-Id: I8e6a0e76ea7f32bda3a8bcd781e75b06d800ec88

* Resolves: #5420 and #5395 
* Target version: master

2022-12-04 21:49 UTC, Andreas-Kainz commented
In general there are more hardcoded icon sizes, but in general it would be only usefull if everything else toolbar, notebookbar, ... size (height) would also change on desktop, mobile, ... so a huge amount of work where you can break a lot of stuff and less output. So from my point of view, the PR is finished.

2023-01-12 09:16 UTC, pedropintosilva requested changes

2023-01-12 09:16 UTC, pedropintosilva commented on browser/css/notebookbar.css
> -	height: 27px;
but in here it seems we are changing from 27 to 24 . Does that affect or cause regressions? I have tested and it seems that is save

2023-01-12 09:16 UTC, pedropintosilva commented on browser/css/notebookbar.css
> -	margin-inline-end: 5px;
Better to add this to another commit. It is unrelated to this commit. Let's please add another with this in and why it is not needed (outdated rules,etc, now being overruled by more recent changes in notebookbar.css:77 etc)

2023-01-12 09:16 UTC, pedropintosilva commented on browser/css/color-palette.css
>  	/* Annotations */
Thanks!

2023-01-12 09:16 UTC, pedropintosilva commented on browser/css/jsdialogs.css
> +	width: var(--icon-size);
Thanks

2023-01-12 09:16 UTC, pedropintosilva commented on browser/css/jsdialogs.css
>  .jsdialog.toolbox {
This seems to be unrelated to this commit. Could you please add a different one with that change in and with the respective commit message?

2023-01-12 09:16 UTC, pedropintosilva commented on browser/css/jsdialogs.css
> +	height: var(--icon-size);
Thanks

2023-01-12 09:16 UTC, pedropintosilva commented on browser/css/jsdialogs.css
> +	width: var(--icon-size) !important;
Thanks

2023-01-12 09:16 UTC, pedropintosilva commented on browser/css/notebookbar.css
> +	width: var(--icon-size);
Thanks

2023-01-12 09:16 UTC, pedropintosilva commented on browser/css/notebookbar.css
> +	height: var(--icon-size);
Thanks

2023-01-12 09:16 UTC, pedropintosilva commented on browser/css/notebookbar.css
> +	height: var(--icon-size-big);
This seems to be unrelated to this commit since we are changing value from 24 to 32px

2023-01-12 09:16 UTC, pedropintosilva commented on browser/css/notebookbar.css
> -
Seems to be unrelated to this commit. Could we please have this in a different commit?

2023-01-12 09:16 UTC, pedropintosilva commented on browser/css/toolbar.css
> +	height: var(--icon-size);
Thanks, but this seems to no only change to css vars but also going from affecting only related children from w2ui-toolbar to every single w2ui-tb-image no matter the parent and even if that are not a w2ui-icon. Was this intended?

2023-01-12 09:16 UTC, pedropintosilva commented on browser/css/toolbar.css
> +	height: var(--icon-size);
Thanks!

2023-02-16 09:28 UTC, pedropintosilva commented
polite ping

2023-05-24 10:45 UTC, Andreas-Kainz commented
There is already btn size value in use. This request isn't needed any more

2023-05-24 10:45 UTC, closed without merging