wsd: support line-breaks in watermark text
CollaboraOnline/online pull request #565
Opened 2020-11-09 00:22 UTC by Ashod

New-line breaks can now be inserted in the watermark
text using
.

The watermark handler member has been fully encapsulated
inside ChildSession, so there is no need to have public
members or circular dependencies (ChildSession owns Watermark
instance, and Watermark takes ChildSession instance to
construct and initialize).

Minor refactoring and const-correctness improvements.

Change-Id: I66188c2619dd7c95b872c87c5144810b06554442

2020-11-09 08:41 UTC, timar commented on kit/Watermark.hpp
> +        LOG_ERR("Watermark [" << text << "] -> [" << _text << "].");
LOG_INF instead?

2020-11-10 11:41 UTC, kendy requested changes
Would be really good to change the LOG_ERR to a less scary loglevel as Andras pointed out.

Also in general, would be great to split functional changes and non-functional ones (like the const correctness) to separate patches - now when we have a review tool that allows to push several patches as part of one PR :-) - but please don't change it for this one, only the LOG_ERR is blocking at the moment.

2020-11-11 01:03 UTC, Ashod commented on kit/Watermark.hpp
> +        LOG_ERR("Watermark [" << text << "] -> [" << _text << "].");
This wasn't intended to go in. Removed.

2020-11-11 07:11 UTC, kendy approved these changes

2020-11-11 07:14 UTC, merged