zotero: added warning for unreachable citation items
CollaboraOnline/online pull request #5766
Opened 2023-01-26 19:41 UTC by lpranam

In cases where zotero item is added by a user and another user opens the doc, if the new user does not have that item in the database, he may fail to do activity related to that item, so we warn the user when we are setting up the zotero

Signed-off-by: Pranam Lashkari <lpranam@collabora.com>
Change-Id: I9056f38334cb8d9b127ddb594adb083d25bd4472

* Target version: master 

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

2023-01-30 10:28 UTC, pedropintosilva reviewed
I didn't manage to have this working.

1. Created a new document
2.  Inserted a citation
3.  Verified that the citation was inserted
4. save and close
5. Head over to Zotero web library and remove that reference
6. Head back to Nextcloud and re-open the document 
7. No warning message appeared

2023-01-30 10:49 UTC, pedropintosilva requested changes

2023-01-30 10:49 UTC, pedropintosilva commented on browser/src/control/Control.Zotero.js
> +					_('It may cause some problems while editing citations or bibliography.'), _('Close'), function() {});
Would be good to do not have the line break in between

2023-01-30 12:44 UTC, lpranam commented
@pedropintosilva good catch, I think it's unlikely that people delete items from their database, so this scenario has low chances and shouldn't be a blocker for this PR.

We rely on userId and groupId to check whether an item is reachable or not, even deleted items have a valid and reachable groupId or userID which is causing the problem here.

2023-01-31 08:49 UTC, timar approved these changes

2023-01-31 08:51 UTC, merged