feature locking: fix custom uno command handling of menu items
CollaboraOnline/online pull request #5797
Opened 2023-02-01 19:34 UTC by lpranam

adding 'uno' field to menu items broke some custom feature handling. Its hard to identify which feature has custom handling so add lockUno field to each item

regression was caused by a6cc06a

Signed-off-by: Pranam Lashkari <lpranam@collabora.com>
Change-Id: Ie6a1201bbff5c383458c1a4c03d4989189b14e3a

* Target version: master 

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

2023-02-01 20:27 UTC, kendy requested changes
Please let's not duplicate everything; it is quite easy to go though the original patch a6cc06ae88980bf039ca5a7417f53899eda412f1 and see where the 'uno' has been added - let's just change those uno:'s to lockUno's, to have this patch minimal & avoid lots of duplication.

2023-02-01 20:43 UTC, lpranam commented
@kendy that's what patch does...

2023-02-01 21:09 UTC, kendy requested changes
I've clarified my concerns - hope it makes more sense now?  Thank you!

2023-02-01 21:09 UTC, kendy commented on browser/src/control/Control.TopToolbar.js
> +			{type: 'button', id: 'bold', img: 'bold', hint: _UNO('.uno:Bold'), uno: 'Bold', lockUno: '.uno:Bold'},
Cases like this are those I'm not happy about - we end up with both uno: 'Bold' and lockUno: '.uno:Bold' ; please let's avoid this :-)

2023-02-01 21:09 UTC, kendy commented on browser/src/control/Control.TopToolbar.js
> -			{type: 'html',   id: 'fontsizes',
Also let's avoid whitespace changes please...

2023-02-02 08:25 UTC, kendy approved these changes
Great - thank you for all the updates, looks good to me!

2023-02-02 08:25 UTC, merged