Insert link
CollaboraOnline/online pull request #5852
Opened 2023-02-14 16:38 UTC by eszkadev

1) Insert > "Pick Link" button is shown when `CheckFileInfo` contains `EnableRemoteLinkPicker`.
    After press `UI_PickLink` is send via postMessage to integrator.
    Action should be finished with sending back `Action_InsertLink` to editor with JSON `{ url: .... }`
    Links then is inserted into document.
    
2) When user clicks on link, preview popup appears with "Loading..." text
    At that time editor sends via postMessage `Action_GetLinkPreview` with JSON `{ url: ... }`
    Integrator should send back   `Action_GetLinkPreview_Resp` with JSON ` { url: ..., title: 'some text', image: 'base64 encoded image'}`

2023-02-20 10:50 UTC, juliushaertl commented
Looks sane from a first look. Note that there would also be a "description" available that we could pass for the link preview.

Filed https://github.com/nextcloud/richdocuments/issues/2813 on our side and @julien-nc will look into this for richdocuments.

2023-02-28 14:08 UTC, eszkadev commented
How it looks now with example image:
![link-popup](https://user-images.githubusercontent.com/5307369/221877467-7a0c676f-e56b-4b72-8eb2-d6a37efbe3f7.png)

2023-02-28 14:44 UTC, pedropintosilva commented
https://github.com/nextcloud/richdocuments/pull/2814

2023-03-01 07:57 UTC, juliushaertl approved these changes
Tested and works like a charm 👍

2023-03-02 09:53 UTC, pedropintosilva approved these changes
Overall I think we can merge this.

- Pick link feature is detected and the button is shown  or in the case of compact view the menu entry is shown
- Insert (normal) hyperlink works: preview is added to the hyperlink's tooltip

However the tooltip is positioned without taking into account the height of its preview
- Before the tooltip would appear on top or bellow depending on the space that is left (within the document)

Plus when inserting Link preview
- it needs the protocol first
- it also replaces the text (the text selection)

2023-03-02 10:25 UTC, pedropintosilva requested changes

2023-03-02 10:25 UTC, pedropintosilva commented on browser/src/map/handler/Map.WOPI.js
> +						value: 'Link'
'Link' hardcoded as discussed

2023-03-02 10:32 UTC, eszkadev commented on browser/src/map/handler/Map.WOPI.js
> +						value: 'Link'
fixed

2023-03-02 10:45 UTC, pedropintosilva requested changes
Thanks, now the text is not being replaced!

but I have found out that now the richdocuments dialog doesn't close at first enter:

https://user-images.githubusercontent.com/65948705/222406609-11f1c9ae-44ae-4107-928b-0a496045dd5a.mp4

2023-03-02 10:48 UTC, pedropintosilva approved these changes
My previous review (need to insert a link again and press enter to make the dialog close) seems to be related to richdocuments only cc: @juliushaertl  (thanks Szymon) However upon refreshing the page the bug dissapears (dialog closes as expected)

2023-03-02 11:27 UTC, merged