Fix not working inotify / restart on coolwsd.xml changes
CollaboraOnline/online pull request #6234
Opened 2023-04-26 06:20 UTC by ralfbecker

* Resolves: # 
* Target version: master 

### Summary
Recently noticed that the inotify I originally added to cause an automatic restart of Collabora, if the coolwsd.xml was changed, no longer works.
Looking at the shell script the problem is obvious.
So, please merge ASAP.

Ralf

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

2023-04-26 12:19 UTC, thebearon approved these changes
Thanks for fixing, Ralf!

2023-04-26 14:33 UTC, thebearon requested changes
On second note, can you please add change-id? This is done automatically when you commit, however the git hooks have to be set up for it. The following steps should do it:
- `scripts/refresh-git-hooks`
- `git commit --amend` (yes, no changes, but the commit message will be updated with the change-id)
- `git push -f` to update your `patch-1` branch on GitHub.

Thanks!

2023-04-26 14:49 UTC, ralfbecker commented
Done, but I don't see anything changed:
```
RalfsMac:online ralf$ git push -f
Everything up-to-date
```
Ralf

2023-04-26 17:48 UTC, thebearon commented
> Done, but I don't see anything changed:

Indeed, nothing has changed. Can you please check `.git/hooks` in the repository, and if `commit-msg`, `post-merge` and `pre-commit` are linking to the corresponding scripts within the repo's `.git-hooks` directory?

2023-04-26 18:08 UTC, ralfbecker commented
Yes they are:
RalfsMac:online ralf$ ls -l .git/hooks/*
lrwxrwxr-x  1 ralf  wheel    29 Apr 26 16:46 .git/hooks/README -> /tmp/online/.git-hooks/README
-rwxrwxr-x  1 ralf  wheel   478 Apr 26 16:45 .git/hooks/applypatch-msg.sample
lrwxrwxr-x  1 ralf  wheel    33 Apr 26 16:46 .git/hooks/commit-msg -> /tmp/online/.git-hooks/commit-msg
-rwxrwxr-x  1 ralf  wheel   896 Apr 26 16:45 .git/hooks/commit-msg.sample
-rwxrwxr-x  1 ralf  wheel  4655 Apr 26 16:45 .git/hooks/fsmonitor-watchman.sample
lrwxrwxr-x  1 ralf  wheel    33 Apr 26 16:46 .git/hooks/post-merge -> /tmp/online/.git-hooks/post-merge
-rwxrwxr-x  1 ralf  wheel   189 Apr 26 16:45 .git/hooks/post-update.sample
-rwxrwxr-x  1 ralf  wheel   424 Apr 26 16:45 .git/hooks/pre-applypatch.sample
lrwxrwxr-x  1 ralf  wheel    33 Apr 26 16:46 .git/hooks/pre-commit -> /tmp/online/.git-hooks/pre-commit
-rwxrwxr-x  1 ralf  wheel  1643 Apr 26 16:45 .git/hooks/pre-commit.sample
-rwxrwxr-x  1 ralf  wheel   416 Apr 26 16:45 .git/hooks/pre-merge-commit.sample
-rwxrwxr-x  1 ralf  wheel  1374 Apr 26 16:45 .git/hooks/pre-push.sample
-rwxrwxr-x  1 ralf  wheel  4908 Apr 26 16:45 .git/hooks/pre-rebase.sample
-rwxrwxr-x  1 ralf  wheel   544 Apr 26 16:45 .git/hooks/pre-receive.sample
-rwxrwxr-x  1 ralf  wheel  1522 Apr 26 16:45 .git/hooks/prepare-commit-msg.sample
-rwxrwxr-x  1 ralf  wheel  2783 Apr 26 16:45 .git/hooks/push-to-checkout.sample
-rwxrwxr-x  1 ralf  wheel  3650 Apr 26 16:45 .git/hooks/update.sample

Only thing I noticed:
RalfsMac:online ralf$ git commit --amend
Commit message is not signed off: .git/COMMIT_EDITMSG
Use 'git commit -s' to sign off the commit message.
Use 'git config commit.signOff true' to automatically sign off commits.

Am I supposed to sign off the commit?

Ralf

2023-04-27 00:24 UTC, thebearon commented
Yes, please do that.

2023-04-28 06:13 UTC, ralfbecker commented
Ok, signed off the commit now.

If that does not work, I don't care that trivial fix of 3 chars is attributed to me, simply change/fix it and I'm happy :) 

Ralf

2023-04-28 13:27 UTC, thebearon approved these changes
Okay, now it's good, thanks for updating the PR!

Only Cypress tests are failing, but that's unrelated, and acceptable at the moment.

2023-04-28 13:27 UTC, merged