dark-mode use correct jquery-ui icons with data-theme value
CollaboraOnline/online pull request #6245
Opened 2023-04-27 21:19 UTC by Andreas-Kainz

dark theme was switched with [data-theme='dark'] instead of prefer-color-scheme so the new setting respect [data-theme='dark'].

#### dropdown icon color is fixed

![Screenshot_20230427_230607](https://user-images.githubusercontent.com/8517736/234993621-546f2849-bb7c-4de3-a5b5-51c55f267315.png)

![Screenshot_20230427_230549](https://user-images.githubusercontent.com/8517736/234993640-ca9f8db6-cf9a-476e-80e3-49e3bfd4003e.png)

Change-Id: I9214fda63f6caea0a36ab8be7c26baf4e1c0f46e

2023-05-01 07:20 UTC, pedropintosilva requested changes
- There are too many curly brackets and spaces (not valid css). Simply ```[data-theme='dark'] .ui-listbox-arrow {```

Nice to have if you can in an additional commit `css: refactor ui-list-box-arrow on dark theme`
- This works as the additional data-theme value is one extra level of specificity thus overriding the generic '''.ui-listbox-arrow {```
  - but please place it after that  so it's easier to understand the priorities when reading the code

2023-05-01 15:10 UTC, Andreas-Kainz commented
I'm not 100% sure what you mean, but it work and the css was cleaned up.

2023-05-02 08:06 UTC, pedropintosilva commented
your first commit was:
```css
[data-theme='dark'] {
	.ui-listbox-arrow {
		background: url('images/jquery-ui-lightness/ui-icons_ffffff_256x240.png') no-repeat transparent;
   }
}
```

but now after your force-pushed it's ok:
```css
[data-theme='dark'] .ui-listbox-arrow {
	background: url('images/jquery-ui-lightness/ui-icons_ffffff_256x240.png') no-repeat transparent;
}
```

2023-05-02 08:06 UTC, pedropintosilva approved these changes

2023-05-02 08:06 UTC, merged