fixed overlay with color name of the gradient in chart sidebar
CollaboraOnline/online pull request #6314
Opened 2023-05-09 13:12 UTC by Darshan-upadhyay1110

fixed overlay with color name of the gradient in chart sidebar 
Change-Id: Ie3c98a908efedfd666cbafa22f21f907f947eb7a

* Resolves: #6293 
* Target version: master 

@pedropintosilva , @GulsahKose

2023-05-23 13:39 UTC, pedropintosilva requested changes
let me push one commit before you do any further changes

2023-05-23 13:39 UTC, pedropintosilva commented on browser/css/jssidebar.css
> +	background-color: transparent;
I think we should make sure the hover status for the menubutton has the same border color and background color as other components such as.jsdialog.ui-listbox:hover 

also `.menubutton.sidebar:hover span` should be improved  ideally to look like any other regular `.ui-tooltip`

2023-05-23 14:54 UTC, pedropintosilva commented
Thanks @Darshan-upadhyay1110 but there were other fixes that were needed before attempting to do this one, and some other PRs that changes some CSS values. So I ended up pushing https://github.com/CollaboraOnline/online/pull/6413/commits 

Could you please test that ^ ? I see there are now a regression WRT width of those components (but it is something unrelated and new introduced by a new width rule that is applied in the overall btn styles so it is not a blocker for my PR)

2023-05-23 14:54 UTC, closed without merging

2023-05-24 04:46 UTC, Darshan-upadhyay1110 commented
okay sure i will test that