browser: impress: introduce slide sorter context menu
CollaboraOnline/online pull request #6398
Opened 2023-05-22 15:59 UTC by lpranam

added context menu entries which works out of the box

Change-Id: Ic0b598a575c4f0fb337ae79bc51cac2330d1115f

* Target version: master 

### Summary

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

2023-05-22 18:30 UTC, timar requested changes

2023-05-22 18:30 UTC, timar commented on browser/src/control/Control.PartsPreview.js
> +						name: _('Duplicate Slide'),
Please use existing translations everywhere, if possible, e.g. here `name: _UNO('.uno:DuplicateSlide', 'presentation')`.

2023-06-01 19:52 UTC, timar requested changes
* Right click does not select slide/page. So the menu command will have effect on the selected slide/page, and not on the slide/page where the context menu appears.
* The style (css) of this context menu is different to other context menus. E.g. the font is different.

2023-06-01 21:20 UTC, timar approved these changes

2023-06-02 08:33 UTC, eszkadev commented on browser/src/control/Control.PartsPreview.js
> +		frame.id = 'preview-frame-part-' + this._idNum;
why do we need this additional `_idNum` variable?  wasn't  `i` already doing the same?
what when we switch to master page and go back? or we add/delete slide?
I think this function will be called again but index will not be reset

2023-06-05 08:32 UTC, closed without merging

2023-06-05 11:53 UTC, lpranam commented
closed in favor of #6529