impress: arrange slide/hide show menu entries better
CollaboraOnline/online pull request #6626
Opened 2023-06-14 18:27 UTC by lpranam

added slide hide/show option in presentation bar
rearranged icons to align them with core UI

Change-Id: Ic4b121ab5d9ab21d8f48e68bb07e51a31442586e

* Target version: master 

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

2023-06-15 07:51 UTC, pedropintosilva requested changes
Thanks for all these improvements :)

The hide/show button in the slide sorter doesn't seem to work as one would expect. It always hides/shows one slide only, doesn't act upon more than one slide (selection) as it happens on core side in the slide sorter

2023-06-15 18:01 UTC, lpranam commented
@pedropintosilva that bug is not related to the button, even notebookbar or menu acts similarly, I'll work on it as follow-up. This PR is just cosmetic

2023-06-15 18:23 UTC, lpranam commented
follow up: #6635

2023-06-16 08:48 UTC, pedropintosilva approved these changes

2023-06-16 08:48 UTC, merged