Up and down arrow work for notebook bar
CollaboraOnline/online pull request #6972
Opened 2023-07-26 10:57 UTC by CosmicOli

Resolves #6933

Change-Id: I1cf696223ff5739e6a48095acbdf3fd778af1ffd

* Resolves: # 
* Target version: master 

### Summary

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

2023-07-26 11:46 UTC, Darshan-upadhyay1110 requested changes
- When document get loaded first time `down arrow key` is not working 
-  and also can we do one thing here like keep function seperated like no decalration of function inside other function. this is verymuch helpful if we need that child function sepratly to use in future ( maybe :) );

2023-07-26 11:48 UTC, Darshan-upadhyay1110 commented
@CosmicOli thanks for the fix. Please check my comment above and let me know for any confusion here.

2023-08-07 10:41 UTC, gokaysatir commented on browser/src/dom/NotebookbarAccessibility.js
> +				}
Thanks for the improvements :)
The reason we removed this from here was: "to not assign accelerator keys before a tab is selected."
If we add this again, there may be conflicts with the tab header accelerator keys.

I think we can modify below part:
    "else if (key === 'ARROWDOWN') {"

We can make it work regardless of the active tab pointers content list. You can check the current tab and find its content and focus on the first element. Without using "this.activeTabPointers.contentList" or any other variable from within the class. Can you check if it is possible?

I will be continuing with the second commit.

2023-08-07 10:57 UTC, gokaysatir requested changes
For the second commit:
I don't think we need this many lines of code. It looks to me like we could add a handler to "toolbar-wrapper" element. That element could catch the "ArrowUp" event and focus on the tab header. It would take only a few lines.

Can you check if it is possible?

2023-08-17 14:09 UTC, gokaysatir approved these changes
Cool :) Thanks for the improvements.

One note as a one-line follow up. When the focus is inside "accessibilityInputElement", autocomplete feature of the browser is activated. Using down and up arrows triggers an autocompletion list.

To prevent this, we can add below line inside initAccessibilityInputElement function:
* this.accessibilityInputElement.autocomplete = 'off';

Thanks :)

2023-08-17 14:21 UTC, Darshan-upadhyay1110 commented
thanks @CosmicOli for the fix.
there is merge confilicts can you please resolve and update the branch with master ?

2023-08-18 10:05 UTC, Darshan-upadhyay1110 approved these changes

2023-08-22 08:38 UTC, pedropintosilva commented
@CosmicOli :
* There is a "merge branch" commit that shouldn't be here  
* Also it seems you didn't rebase your changes on top of latest master

```
*   dcf5e8bfb1	CosmicOli	Fri Aug 18 10:13:56 2023 +0100	Merge branch 'master' into private/oli/up-and-down-arrow
|\  
| * c3aaae077f	Darshan-upadhyay1110	Wed Aug 16 14:33:26 2023 +0530	Add missing dark mode toggle in mobile view
| * 3103ab5c66	Pedro Pinto Silva	Thu Aug 17 13:34:23 2023 +0200	Add missing rename document icon
| * a1a6817e4d	Aron Budea	Thu Aug 17 02:56:54 2023 +0200	unocommands.py: Treat JS/TS files as UTF-8
| * 89f283c676	Caolán McNamara	Wed Aug 16 21:33:53 2023 +0100	cool#7102 fix 2nd presentation under chrome not appearing
| * 851c232531	Caolán McNamara	Wed Aug 16 11:16:32 2023 +0100	cid#318843 COPY_INSTEAD_OF_MOVE
| * 62504735ea	Caolán McNamara	Tue Aug 15 16:13:58 2023 +0100	cid#318868 silence bogus Double free
| * a45b4e875f	Gökay Şatır	Wed Aug 16 13:09:44 2023 +0300	Add accessibility keys for insert and format tabs.
| * 10b58a0a4f	Gökay Şatır	Wed Aug 16 12:07:59 2023 +0300	Add accessibility definitions to draw UI.
| * 9fd60f55e0	Gökay Şatır	Wed Aug 16 12:47:36 2023 +0300	Update Cypress tests.
| * b304644be4	Gökay Şatır	Tue Aug 15 15:25:33 2023 +0300	Calc - Add remaining tabs' accessibility definitions.
| * 9436512afb	Gökay Şatır	Tue Aug 15 13:53:03 2023 +0300	Calc File and Home tabs' accessibility definitions.
| * 33abd9c437	Gökay Şatır	Tue Aug 15 13:52:07 2023 +0300	Initialize contentlist with empty array.
| * 49354607e0	Gökay Şatır	Tue Aug 15 12:35:53 2023 +0300	Re-enable multi-language support on accessibility definitions.
| * 34635de5d4	Gökay Şatır	Tue Aug 15 12:11:35 2023 +0300	Calc: Add ids to notebookbar definitons & simplify definitons.
| * ac8440fea7	Szymon Kłos	Tue Aug 15 14:17:15 2023 +0200	jsdialog: add minimal size for treeview
| * c4183d2709	Rash419	Mon Aug 14 21:43:17 2023 +0530	android: fix app crashes after closing the document
| * 6a7b98af8a	Rash419	Tue Aug 15 21:26:18 2023 +0530	fix: cell border preview in mobile wizard
| * 639068e3fe	Rash419	Tue Aug 15 18:42:23 2023 +0530	impress: remove unused mobile-slide-sorter - to show previews we use slide-sorter element   and presentation-controls-wrapper as container
| * 03fa9d9c86	Szymon Kłos	Tue Aug 15 12:19:29 2023 +0200	jsdialog: always execute close message from server
| * 2eda4740ca	Szymon Kłos	Tue Aug 15 09:32:33 2023 +0200	Don't show presentation on iOS in small frame
| * 9a0b34f8fb	Szymon Kłos	Tue Aug 15 14:34:40 2023 +0200	jsdialog: fix error on insert_button
| * 42df0dac71	Caolán McNamara	Tue Aug 15 11:31:45 2023 +0100	cid#318842 silence Unchecked return value
| * ce0c11f09f	Caolán McNamara	Tue Aug 15 11:23:23 2023 +0100	cid#318866 can elide the temporary here
| * 461fe6a630	Caolán McNamara	Tue Aug 15 11:19:17 2023 +0100	cid#318940 Big parameter passed by value
| * eaa2b0cf2f	Caolán McNamara	Mon Aug 14 14:59:58 2023 +0100	cid#318821 COPY_INSTEAD_OF_MOVE
| * 5dcf65f5c6	Caolán McNamara	Mon Aug 14 14:58:37 2023 +0100	cid#318893 COPY_INSTEAD_OF_MOVE
| * 68135a4682	NickWingate	Mon Aug 14 14:44:55 2023 +0100	Rename with file default when given unspecified extension
| * 24ac74db4f	NickWingate	Mon Jul 31 16:41:57 2023 +0100	Add rename document to notebookbar and menubar
| * 478fd19ccc	Caolán McNamara	Mon Aug 14 12:48:02 2023 +0100	cid#318850 Unchecked return value
| * 3502e1d006	Caolán McNamara	Mon Aug 14 12:21:36 2023 +0100	cid#318903 Dereference after null check
| * 6062342827	Caolán McNamara	Mon Aug 14 12:15:26 2023 +0100	cid#318980 COPY_INSTEAD_OF_MOVE
| * 7d6619be90	Miklos Vajna	Mon Aug 14 08:19:13 2023 +0200	wsd, coding style: document double review for security
| * 41bdf1ece8	Rash419	Mon Aug 14 21:33:55 2023 +0530	admin: remove fixed width and height attr from svg
| * 65f6f46093	Rash419	Mon Aug 14 19:34:14 2023 +0530	admin: use humanizeMem in adminClusterOverview.js
| * 555a07db70	Pedro Pinto Silva	Mon Aug 14 15:58:45 2023 +0200	AdminCluster: Use proper card headers for title instead
| * efe874f89c	Ashod Nakashian	Sun Aug 13 08:35:16 2023 -0400	wsd: simplify shutdown and termination flagging
| * 35dda35f9d	Ashod Nakashian	Sat Aug 12 16:57:04 2023 -0400	wsd: move statics into anonymous namespace
| * e660bb8e66	Gökay Şatır	Mon Aug 14 14:21:05 2023 +0300	When document layer is not ready and socket message is not delayed, message is lost.
| * 8570a03555	Gökay Şatır	Mon Aug 14 12:27:13 2023 +0300	Correct menubutton control id calculation.
| * 3d1725ea44	Gökay Şatır	Fri Aug 11 17:47:29 2023 +0300	Cypress updates.
| * 7d084e40cb	Gökay Şatır	Thu Aug 10 15:45:29 2023 +0300	Update cypress tests.
| * a3d9abcc20	Gökay Şatır	Thu Aug 10 10:37:54 2023 +0300	Move all accessibility definitions from notebookbaraccessibilitydefinitions into control.notebookbarwriter.
| * 7d0f7d7378	Gökay Şatır	Wed Aug 9 11:21:25 2023 +0300	writer insert tab keys are added. Replaced id based checks with uno command ones. Removed unnecessary function from notebookbaraccessibility. We don't use automatic id assignments any more.
| * 1a2500c8d3	Gökay Şatır	Tue Aug 8 15:46:49 2023 +0300	Merge accessibility definitions with notebookbar definitions.
| * 939a7a0301	Gökay Şatır	Mon Aug 7 16:38:46 2023 +0300	Simplify notebookbarwriter and tab page containers.
| * 2cc714705a	Gökay Şatır	Mon Aug 7 16:05:26 2023 +0300	Remove access key assignments from jsdialogs.
| * f8e53bd851	Gökay Şatır	Mon Aug 7 15:31:21 2023 +0300	Assign tab ids while defining tabs.
| * 6682a2a527	Caolán McNamara	Thu Aug 10 09:56:56 2023 +0100	cid#318900 Out-of-bounds write
| * 307818ba1c	Caolán McNamara	Thu Aug 10 09:42:00 2023 +0100	cid#318834 Missing move assignment operator
| * f7e121e2ea	Caolán McNamara	Thu Aug 10 09:37:41 2023 +0100	cid#318953 COPY_INSTEAD_OF_MOVE
| * 4b9cbab33d	Szymon Kłos	Fri Aug 11 09:17:01 2023 +0200	jsdialog: fix spinfield precision detection
| * eee6e49e8a	Szymon Kłos	Sat Aug 12 12:52:39 2023 +0200	cypress: fix unstable alignment test
| * 697f4a6109	Szymon Kłos	Sat Aug 12 10:10:06 2023 +0200	cypress: fix failing table tests
| * b85eb1b03f	Szymon Kłos	Fri Aug 11 20:55:44 2023 +0200	cypress: fix svg text-decoration detection
| * e6a06eae1c	Shehr Bano	Wed Aug 9 22:58:50 2023 +0500	FIX #7037: JSDialog: label vs textarea vs input field inconsistent paddings
| * 16b8bead39	Pedro Pinto Silva	Fri Aug 11 11:35:07 2023 +0200	Revert "Add action for detecting code duplicates"
| * 47f4305050	Rash419	Thu Aug 10 13:39:45 2023 +0530	fix: cursor jump when hyperlink popup clicked in mobileview
| * 912dfcd08e	Caolán McNamara	Wed Aug 9 21:49:20 2023 +0100	autofill onMouseDown doesn't generate working event position for hidpi
| * a42adac98f	Ashod Nakashian	Fri Aug 4 05:30:57 2023 -0400	wsd: add the web-server URL to the media-src list
| * 85ee03f98f	Andras Timar	Wed Aug 9 20:01:33 2023 +0200	CollaboraOnline#6546 enable automatic color in default paragraph style
| * c89cccfc7a	Pedro Pinto Silva	Fri Aug 4 12:58:49 2023 +0200	Welcome: allow scroll bar
| * 96a7cfb25e	Marco Cecchetti	Mon Jul 10 12:14:17 2023 +0200	a11y: provide info about current table and cell to screen reader
| * 7825f82ce1	Darshan-upadhyay1110	Wed Aug 9 18:10:32 2023 +0530	Remove open_local_editor button in tablet view
| * 5185b7bedf	Caolán McNamara	Wed Aug 9 14:18:47 2023 +0100	cid#318934 silence Untrusted loop bound
| * d79d86ed91	Caolán McNamara	Wed Aug 9 14:10:21 2023 +0100	cid#318844 Dereference before null check
| * 2a8910a941	Caolán McNamara	Wed Aug 9 14:05:33 2023 +0100	addPollFor default arg is now always explicitly passed
| * c593a0bde5	Caolán McNamara	Wed Aug 9 14:04:57 2023 +0100	replaySync is unused
| * b6f87b06e3	Caolán McNamara	Wed Aug 9 13:59:41 2023 +0100	cid#322475 COPY_INSTEAD_OF_MOVE
| * 1cd88f217e	Caolán McNamara	Wed Aug 9 13:52:02 2023 +0100	cid#321976 AUTO_CAUSES_COPY
| * 5dcce1965e	Rash419	Wed Aug 9 14:59:08 2023 +0530	android: enable dark mode in documents
| * c2192b4a67	Pedro Pinto Silva	Wed Aug 9 13:13:05 2023 +0200	Screen reader doesn't properly report tab names in Tab View UI
| * 0c61164 [...]

2023-08-22 16:02 UTC, merged