Add support for URP messages in COOLWSD
CollaboraOnline/online pull request #6992
Opened 2023-07-31 14:39 UTC by Minion3665

Change-Id: Idadfe288a78cfd72b01253dfdade150d506e3f05

* Resolves: # 
* Target version: master 

### Summary

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

2023-08-09 11:14 UTC, eszkadev commented on kit/ChildSession.cpp
> +        if (length < 4) return false;
Later when you will prepare final PR, please make sure formatting is ok. Here it uses different style than we use in c++ code.
if () {
}
vs
if ()
{
}

2023-08-22 16:03 UTC, mmeeks commented on kit/ChildSession.cpp
>      if (std::string(std::getenv("ENABLE_WEBSOCKET_URP")) == "true")
It is prolly better to get a StdlyCapsGlobal here setup on start-up of the kit; just how 'AnonymizationSalt' is setup - copy how that's done through the code - this global env. var is not really a per-instance member concept =)

2023-09-29 17:16 UTC, mmeeks requested changes
This looks a lot more sensible and has waaay fewer scary Mutexen in it :-) so awesome!
Does it work ?
Ultimately I'd really like to touch the net/Socket code as little as possible, if possible - I'd hope that shouldn't be necessary. We have hard-coded wakeup socket, and then everything should be uniform: Unix Domain Sockets, IPv6 / IPv4 / listening server sockets / inotify pipes etc. - I don't think we want to change that.
But great to see it so nearly there ! =)

2023-09-29 17:16 UTC, mmeeks commented on net/Socket.hpp
> -        char adata[CMSG_SPACE(sizeof(int))];
Fun =)

2023-09-29 17:16 UTC, mmeeks commented on wsd/COOLWSD.hpp
> +                return false;
This seems odd - can't we use a Stream to write from the coolwsd side and shuffle the data across ?

2023-09-29 17:16 UTC, mmeeks commented on net/Socket.cpp
> +    bool hasURP = _urpFD != -1;
I'm a tad surprised we can't use a normal StreamSocket for the URP  thing and add that to the SocketPoll in the normal way - did you try without this ? =)

2023-10-02 07:37 UTC, caolanm commented
Oh yeah, it certainly works. I'll move stuff into some sort of StreamSocket based solution.

2023-10-02 19:06 UTC, mmeeks approved these changes
Looks really nice =) thanks Caolan !

2023-10-03 09:15 UTC, merged

2023-10-17 16:07 UTC, caolanm commented
I'll just stash here a standalone demo modified to use collabora-online and this feature, based on the example of https://bugs.documentfoundation.org/show_bug.cgi?id=152261 

[officepb-collabora-online.zip](https://github.com/CollaboraOnline/online/files/12935390/officepb-collabora-online.zip)