Fix 'manage changes' dialog expanding infinitely
CollaboraOnline/online pull request #7112
Opened 2023-08-18 13:11 UTC by Minion3665

A regression in #7011 caused the manage changes dialog to continue expanding when new elements were added, no matter how big it got. This would cause you to be unable to see all the changes when there were a lot of them because you could not scroll through the list. This patch fixes the scrolling, without making the list area very small again.

Change-Id: Ib29fb161522773ea9893b7bc21d06aab19b74c52

* Target version: master 

### Checklist

- [x] Code is properly formatted
- [x] All commits have Change-Id
- [ ] I have run tests with `make check`
- [x] I have issued `make run` and manually verified that everything looks okay
- [x] Documentation (manuals or wiki) has been updated or is not required

2023-08-18 13:19 UTC, eszkadev commented on browser/css/jsdialogs.css
> +#AcceptRejectChangesDialog .ui-grid {
could you move all these rules to the end of file
and before add separation comment with name of the dialog
that would make things grouped, here we have general rules for all dialogs

2023-08-21 08:12 UTC, pedropintosilva requested changes
Thanks @Minion3665 

I just don't understand one thing. Why the max-height: none was set in the first place.. Meaning wouldn't be enough of a fix to remove `max-height: none;` and this inherit the general max-height rule coming from the ui-treeview-body?

Otherwise, and if we need to set all these in the css afterwards in a case by case then we should maybe improve the widget itself instead.

2023-08-21 08:41 UTC, Minion3665 commented
> Thanks @Minion3665
> 
> I just don't understand one thing. Why the max-height: none was set in the first place.. Meaning wouldn't be enough of a fix to remove `max-height: none;` and this inherit the general max-height rule coming from the ui-treeview-body?
> 
> Otherwise, and if we need to set all these in the css afterwards in a case by case then we should maybe improve the widget itself instead.

@pedropintosilva So, you'd think so, but that was what was causing https://github.com/CollaboraOnline/online/issues/6977... in this case you wanted to have the treeview filling the space so we can't limit it to the normal max height...

Improving the element so it always fills the available space is an option, would you like me to look into doing that instead (possibly in a separate issue so we can get this merged for Richard Brock)?

2023-08-21 12:20 UTC, pedropintosilva commented
I would prefer to also fix this as initially I wished (via CSS grid) but I would like to steer away from adding it in a case by case basis.

This PR works better but if this will not stay in the long run wouldn't it be better to just remove the max-height for now?

```diff
 .jsdialog #writerchanges .ui-treeview-body {
        min-height: 300px;
-       max-height: none;
 }
```
| With This PR| Removing max-height|
| --- | --- |
| ![with-PR7112](https://github.com/CollaboraOnline/online/assets/65948705/a5e6dc44-214b-4fbc-a77e-35664776a269) | ![just-removing-max-height](https://github.com/CollaboraOnline/online/assets/65948705/e7e58de9-c684-45c3-be52-710c9ed774a7) |

> So, you'd think so, but that was what was causing https://github.com/CollaboraOnline/online/issues/6977...

And I think we wouldn't see this problem again because we keep the min-height.

Thus I'm not against merging this but up to @eszkadev

2023-08-22 14:16 UTC, Minion3665 commented
I've replaced this with the code as Pedro suggested, as well as moving it down so it conforms with the earlier review comment from Szymon... let's look into using something closer to the css that I had before for doing this to treeviews not on a case-by-case basis sometime in the future

2023-08-22 14:25 UTC, eszkadev approved these changes

2023-08-22 17:04 UTC, merged