Private/gokay/impress accessibility definitions
CollaboraOnline/online pull request #7115
Opened 2023-08-18 13:42 UTC by gokaysatir

* Resolves: # 
* Target version: master 

### Summary

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

2023-08-23 09:46 UTC, pedropintosilva requested changes

2023-08-23 09:46 UTC, pedropintosilva commented on browser/src/control/Control.NotebookbarImpress.js
> +					'id': 'file-saveas',
the button is coming out without icon please add icon alias:
```diff
diff --git a/browser/src/control/Control.JSDialogBuilder.js b/browser/src/control/Control.JSDialogBuilder.js
index 6abb6e6627..d45d330458 100644
--- a/browser/src/control/Control.JSDialogBuilder.js
+++ b/browser/src/control/Control.JSDialogBuilder.js
@@ -2320,6 +2320,7 @@ L.Control.JSDialogBuilder = L.Control.extend({
 		}
 
 		var iconURLAliases = {
+			'file-saveas': 'saveas',
 			'home-search': 'recsearch',
 			'addmb-menu': 'ok',
 			'closetablet': 'view',
```

Also the save as should be a dropdown but it looks like this now:
![image](https://github.com/CollaboraOnline/online/assets/65948705/29865db7-b54d-4b87-88d2-2153d439785b)

2023-08-23 09:46 UTC, pedropintosilva commented on browser/src/control/Control.NotebookbarImpress.js
> +				'id': 'insert-insert-smart-picker',
please add 
```js
'class': 'unoremotelink'.
```

2023-08-23 09:46 UTC, pedropintosilva commented on browser/src/control/Control.NotebookbarImpress.js
> +				'accessibility': { focusBack: true, combination: 'TU', de: null }
please add:
```js
'class': 'unotoggleuimode',
```

2023-08-25 16:24 UTC, eszkadev commented on browser/src/dom/NotebookbarAccessibility.js
> +			console.log('display: ' + anchorElement.style.display);
console log, to delete I think?

2023-08-25 16:26 UTC, eszkadev commented on browser/src/control/Control.NotebookbarImpress.js
> +				'accessibility': { focusBack: false, combination: 'W', de: null }
what is de? why we have to assign null there?

2023-08-28 10:52 UTC, eszkadev approved these changes

2023-08-28 20:45 UTC, merged