Add accessKey properties for save buttons of shortcuts toolbox.
CollaboraOnline/online pull request #7157
Opened 2023-08-24 13:30 UTC by gokaysatir

Change-Id: I24d892e0618d7105062e794c032fb8f96f76ccf3

* Resolves: # 
* Target version: master 

### Summary

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

2023-08-25 06:39 UTC, gokaysatir commented
@pedropintosilva hello, I assigned "X" button to save shortcut but it's like a random one. "S" key conflicts with "References" tab. Can you suggest a better shortcut key or can we merge this onne? Thanks.

2023-09-06 11:56 UTC, pedropintosilva commented on browser/src/control/Control.Notebookbar.js
> +						'accessKey': 'X'
Can we change it for `1`?

2023-09-06 11:56 UTC, pedropintosilva requested changes

2023-09-06 11:56 UTC, pedropintosilva commented on browser/src/control/Control.NotebookbarDraw.js
> +							'accessKey': 'X'
Can we change it for `1`?

2023-09-08 09:17 UTC, merged