Add cli option to use settings from env variables
CollaboraOnline/online pull request #7160
Opened 2023-08-24 14:20 UTC by Minion3665

Change-Id: I75762ad620132037523fa82167a3ff17075c7027

* Target version: master 

### Summary
Currently [in docker it is possible to do configuration through
environment variables](https://col.la/dockercodeconfigviaenv), which
works using the start-collabora-online.sh start-collabora-online.pl
scripts. This PR lets COOLWSD listen to the same environment
variables directly

### TODO

- [ ] ...

### Checklist

- [x] Code is properly formatted
- [x] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

2023-09-11 08:35 UTC, timur-g commented
Can you please explain how this will work?

2023-09-11 09:26 UTC, Minion3665 commented
@timur-g 
> Can you please explain how this will work?

Sure thing! The idea is to be able to replace the work done by the docker scripts (see https://github.com/CollaboraOnline/online/blob/master/docker/from-packages/scripts/start-collabora-online.sh) directly in wsd... 
```sh
if test -n "${username}"; then
    perl -pi -e "s/<username (.*)>.*<\/username>/<username \1>${username}<\/username>/" /etc/coolwsd/coolwsd.xml
fi
if test -n "${password}"; then
    perl -pi -e "s/<password (.*)>.*<\/password>/<password \1>${password}<\/password>/" /etc/coolwsd/coolwsd.xml
fi
if test -n "${server_name}"; then
    perl -pi -e "s/<server_name (.*)>.*<\/server_name>/<server_name \1>${server_name}<\/server_name>/" /etc/coolwsd/coolwsd.xml
fi
if test -n "${dictionaries}"; then
    perl -pi -e "s/<allowed_languages (.*)>.*<\/allowed_languages>/<allowed_languages \1>${dictionaries:-de_DE en_GB en_US es_ES fr_FR it nl pt_BR pt_PT ru}<\/allowed_languages>/" /etc/coolwsd/coolwsd.xml
fi
```

This will let us remove those scripts entirely from docker, but we still want to keep the ability to add settings from environment variables because it makes configuring docker easier.

The idea here is to add an extra option (`--use-env-vars`) which will get COOLWSD to look at the same environment variables that the scripts did directly. Does that answer the question?

2023-09-11 10:03 UTC, timur-g commented
Thanks, just one more. Will you update documentation?

2023-09-11 12:02 UTC, Minion3665 commented
@timur-g 
> Thanks, just one more. Will you update documentation?

thanks for the reminder! I've updated the manpage to add the new option now. I'd like to edit https://sdk.collaboraonline.com too but I don't know where the source to that is... do you?

2023-09-11 13:38 UTC, timur-g commented
No, but I guess @thebearon knows.

2023-09-22 21:55 UTC, timar approved these changes

2023-09-22 22:10 UTC, timar requested changes
* remoteconfigurl is missing
* domain is missing (although it was deprecated by alias_groupX so probably we can skip it)

2023-09-22 22:13 UTC, timar commented
> * remoteconfigurl is missing
> * domain is missing (although it was deprecated by alias_groupX so probably we can skip it)

I added remoteconfigurl.

2023-09-23 07:26 UTC, timar approved these changes

2023-09-23 10:44 UTC, merged