feat(helm): add logging-operator flows
CollaboraOnline/online pull request #7363
Opened 2023-10-04 12:15 UTC by genofire

Change-Id: I0bd8de7b4dfd974c1f9e0eeb24eefc229f70431f

* Resolves: # 
* Target version: master 

### Summary

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

2024-01-02 20:54 UTC, genofire commented
Ping @Rash419

2024-01-03 10:22 UTC, Rash419 requested changes

2024-01-03 10:45 UTC, genofire commented on kubernetes/helm/collabora-online/templates/flow.yaml
> +              # wsd-00001-00092 2023-04-20 15:34:56.729826 +0000 [ docbroker_001 ] ERR  Unauthorized Request while starting session on https://nextcloud.example.org:443/collabora/lptFile123.odt for s
done

2024-01-11 08:34 UTC, Rash419 approved these changes
Looks good

2024-01-15 06:02 UTC, Rash419 commented
Merging this. There is no way it can affect the cypress/unit tests

2024-01-15 06:03 UTC, merged