Allow http Range header for media files
CollaboraOnline/online pull request #7367
Opened 2023-10-04 15:13 UTC by Minion3665

The range header allows a client to specify that they would like only part of a file, e.g. only the first 1000 bytes of a video. When playing video on Apple devices (Macs, iPads, iPhones etc.) this is required to avoid Safari rejecting the video as broken. This is the first part of a fix to embedded videos on Safari.

This commit does not implement specifying multiple ranges at once (e.g. byte=0-9,-100 to get the first 10 and last 100 bytes).

This feature is necessary to play video on Apple devices, but it is not sufficient. In particular, I believe some further client-side fixes will be needed to make the video play properly.

Change-Id: Id89a06d374b7d0efbf2b3184d8618df61684dcb6

* Resolves: # 
* Target version: master 

### Checklist

- [ ] Code is properly formatted
- [x] All commits have Change-Id
- [ ] I have run tests with `make check`
- [x] I have issued `make run` and manually verified that everything looks okay
- [x] Documentation (manuals or wiki) has been updated or is not required

2023-10-04 17:10 UTC, mmeeks requested changes
Headers etc. look good - but somehow I'd expect to have a seek in the asyncUpload that would not load the whole video into memory etc. and to honor _start and _end not just in the generated headers: or did I miss something ? =)

2023-10-04 17:11 UTC, mmeeks commented
Overall great catch and nice change though - but this code is @Ashod baby so prolly he has more requests =)

2023-10-05 08:17 UTC, Minion3665 commented
> Headers etc. look good - but somehow I'd expect to have a seek in the asyncUpload that would not load the whole video into memory etc. and to honor _start and _end not just in the generated headers: or did I miss something ? =)

yep, you're absolutely right, thanks for catching that!

2023-10-05 10:16 UTC, mmeeks approved these changes
Looks great to me - but still, I'd like @Ashod 's take =)

2023-10-10 10:24 UTC, Ashod commented on wsd/COOLWSD.cpp
> +            docBroker->handleMediaRequest(request, socket, tag);
Let's pass in the `range`. No reason to depend on `Poco::Net::HTTPRequest`  to read a header.

2023-10-11 11:08 UTC, mmeeks commented
So - we should get this merged for the release if we can to get testing - lets get it in now & improve on it in a follow-up if necessary :_)

2023-10-11 12:18 UTC, Minion3665 commented
> @mmeeks 
> So - we should get this merged for the release ... lets get it in now

Alright, I've deleted the half-made unit test file so I can work on that in a followup. Would you like to wait for @Ashod to take another look at it after I addressed the comment on passing the header in directly or should we merge when green?

2023-10-11 14:02 UTC, mmeeks commented
Lets merge it as long as the unit test comes next :-) thanks Skyler.

2023-10-11 15:09 UTC, merged