Change the local storage setting name 'CompactMode' to 'compactMode'
CollaboraOnline/online pull request #7391
Opened 2023-10-09 19:32 UTC by timar

We want to re-force the choice, i.e. people who mistakenly set their UI to compact mode, now will get tabbed mode and can decide, if they like it better or not.

Change-Id: Ic5810321abf2cbc3996478816fe153d848c66c71

2023-10-09 19:48 UTC, mmeeks reviewed
Nice commit; Of course - keeping the StdlyCaps consistent but choosing another name might be less confusing in the long run - but this is fine.

2023-10-11 10:34 UTC, pedropintosilva approved these changes

2023-10-11 10:46 UTC, pedropintosilva requested changes
I see @mmeeks .

Maybe best to use something like `CompactView` since anyhow we refer to that both in the code comments and in the UI as a view. This way we would keep the alternating caps format.

2023-10-11 10:53 UTC, mmeeks approved these changes
Lets get it in quick.

2023-10-11 10:54 UTC, merged