JSDialog: Dialogs shouldn't be taller than viewport
CollaboraOnline/online pull request #7418
Opened 2023-10-12 09:13 UTC by pedropintosilva

Don't allow dialogs to grow taller than the web browser's viewport
instead,
 - Set (for dialog's content) a max of 90% of the View height and subtract the dialog's
header. This way the header with the close button stays always visible
 - Set overflow accordingly so it can be  scrollable

Signed-off-by: Pedro Pinto Silva <pedro.silva@collabora.com>
Change-Id: I61a2a41d8b1198fe00b939427cde43d247dc08bb

2023-10-12 12:28 UTC, GulsahKose approved these changes

2023-10-12 13:31 UTC, eszkadev commented
For me doesn't work (no scrollbar, cannot scroll using mouse, not visible bottom of the dialog if window is small):

[resize-2023-10-12_15.30.37.webm](https://github.com/CollaboraOnline/online/assets/5307369/700647d2-c871-40de-a5c4-c0bf36e72838)

2023-10-12 13:32 UTC, eszkadev requested changes
.

2023-10-13 08:06 UTC, pedropintosilva commented
> For me doesn't work (no scrollbar, cannot scroll using mouse, not visible bottom of the dialog if window is small):
> resize-2023-10-12_15.30.37.webm

thanks, please check again. It seems when I tested I was using a theme/customizations that somehow bypassed that. I found the culprit. `!important` needs to be added

2023-10-13 09:16 UTC, eszkadev approved these changes
now is ok

2023-10-13 11:52 UTC, merged