avoid recreating the core notebookbar when we don't have to
CollaboraOnline/online pull request #7494
Opened 2023-10-19 19:24 UTC by caolanm

this is inspired by trying to reproduce:

https://github.com/CollaboraOnline/online/issues/7428

Where I see that we tear down and recreate the notebookbar when we switch from light to dark mode, and we recreate it when Zotero support is enabled.

Change-Id: I4a95af357a95931df12ff96d9378b235d27e3eaf

* Resolves: # 
* Target version: master 

### Summary

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

2023-10-19 20:26 UTC, eszkadev commented on browser/src/control/Control.UIManager.js
> +			var wasNotebookbarLoadedOnCore = this.notebookbar && this.notebookbar._isNotebookbarLoadedOnCore;
there is method for that: `notebookbar.isInitializedInCore()` to not expose internals outside

2023-10-19 20:47 UTC, eszkadev requested changes
it breaks widgets in notebookbar, repro:
1. open writer
2. switch mode light/dark
3. switch notebookbar to home tab, try font selector, style previews, font size
Result: none of the widgets received update from the core so they are empty/have initial values

We would need to cache last values and inject into "template" from which they are created, or force widgets to send update message.

2023-10-20 07:07 UTC, eszkadev commented
btw, do we need to refresh notebookbar on theme switch at all?
I think it will apply dark theme automatically because different CSS rules will be applied. I don't think any widget has different content after rebuild. Maybe we can just skip it.

2023-10-20 11:41 UTC, caolanm commented
Checking just simply skipping this.refreshNotebookbar in refreshAfterThemeChange on a theme switch, then the notebookbar has the wrong icons. Looks to me that we set these icons with an explicit "dark" in their path (or not) during the building and they don't have css rules for dark/light so we have to destroy and recreate the browser notebookbar to get the right icons. If we then don't recreate the core one then the browser one has the empty menus etc as mentioned above.

var icon = data.icon ? data.icon : builder._createIconURL(data.command); is where we set the icons

2023-10-23 06:37 UTC, eszkadev commented
I see, I have idea how to reload icons without rebuilding notebookbar. I will try to do that.

2023-10-23 13:57 UTC, eszkadev commented
Reload of icons on theme change: https://github.com/CollaboraOnline/online/pull/7513

2023-10-23 18:36 UTC, closed without merging

2023-10-23 18:36 UTC, caolanm commented
https://github.com/CollaboraOnline/online/pull/7513 is better, so close this