Modified the edit mode to allow the user edit directly on cell when t…
CollaboraOnline/online pull request #765
Opened 2020-11-24 15:24 UTC by Ezinnem

…he keyboard is availble

Signed-off-by: Ezinne Nnamani <nnamani.ezinne@collabora.com>
Change-Id: I2ea3e9248eacaf3923ef1633ac5aa8838241655e
Signed-off-by: Ezinne Nnamani <nnamani.ezinne@collabora.com>

* Resolves: # 
* Target version: master 

### Summary

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

2020-11-24 15:47 UTC, Ashod requested changes
Thanks Ezinne for the patch! Looks good (as discussed) but I think we need to isolate it (see comment in code).

Another suggestion is to make the commit message much more detailed and descriptive, so others can understand 1) what the issue was, 2) how you fixed it, 3) why this approach and not another, 4) optional: any other comments/caveats for the future (for example a todo to improve something). Also, making the title message short with a longer body is best for readability. Notice how we often prefix the title message with the domain/area so that others would know what this change is about without looking at the patch itself.

Here is a suggestion (feel free to modify):

leaflet: calc: allow keyboard input on mobile without tapping

On mobile Calc required tapping a cell to start editing.
To allow for seamless editing right after clicking the
edit button in mobile view, we need to send Core F2,
which enters edit mode and we get the cursor position.

The reason we need to send F2 explicitly, even though
this isn't needed on desktop, is because in mobile we
start in read-only mode, and therefore we don't have
the cursor position. So we need to initiate editing when
the user clicks the edit button and enables editing again.

2020-11-24 15:47 UTC, Ashod commented on loleaflet/src/control/Permission.js
> +			}
This is great for Calc, but we probably don't want (or need) to send F2 for Writer and Impress.

2020-11-25 13:54 UTC, thebearon commented
Let me point out that the original request was about staying in cell edit mode when you tap/press enter after entering content in a cell, and not about switching to editing the file after the initial read-only view.

2020-11-25 20:54 UTC, Ashod commented on loleaflet/src/control/Permission.js
> +				if (this._docLayer._docType === 'spreadsheet') {
Don't we want to take focus for all document types? F2 is meaningful only for Calc, but the focus is for all.

Also, I think there is .isCalc() helper function somewhere. Can you check if we can use it here please? Comparing with strings is error prone, so best to minimize/avoid them.

2021-11-03 15:18 UTC, kendy commented
Agreed with @Ezinnem and @Ashod to close this.  Thank you for the patch either way! :-)

2021-11-03 15:18 UTC, closed without merging