Mobile: Insert comment layout is too narrow and doesn't occupy full height
CollaboraOnline/online pull request #7719
Opened 2023-11-24 15:07 UTC by codewithvk

Change-Id: Ibb6beff5659f5240ff2b49897e8a491f08933691

* Resolves:
* Target version: master 

Comment:
![Screenshot from 2023-11-24 20-31-18](https://github.com/CollaboraOnline/online/assets/61119120/f20b894d-7032-4b1f-9219-96f53bbce797)
![Screenshot from 2023-11-24 20-31-56](https://github.com/CollaboraOnline/online/assets/61119120/c3783b6f-eed5-452c-8bb1-0c92f0293101)

HyperLink: 
![Screenshot from 2023-11-24 20-32-32](https://github.com/CollaboraOnline/online/assets/61119120/184dd607-88dd-4ffe-866d-7cc98cbe3b77)

2023-12-14 18:03 UTC, codewithvk commented
> This doesn't fix the bug. We want ![image](https://private-user-images.githubusercontent.com/65948705/290563595-42687977-4b22-4d1d-ae04-ae71df3bed61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NzY4NzgsIm5iZiI6MTcwMjU3NjU3OCwicGF0aCI6Ii82NTk0ODcwNS8yOTA1NjM1OTUtNDI2ODc5NzctNGIyMi00ZDFkLWFlMDQtYWU3MWRmM2JlZDYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDE3NTYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxNTA0YzI4ZWI0MDg1OTUyNjNiNDdjZTgwYzI5OGJkMTM0NGQyMTRmYmMyN2I0MWE5ZjI3N2JmZDUzMGI2NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tkMxF1-o7PoDdsWGxjRHG-SVfa84GcHr7vGbQaFibIY) to be ![image](https://private-user-images.githubusercontent.com/65948705/290563683-888ae46e-da0f-46f0-86d2-b6fa040147a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NzY4NzgsIm5iZiI6MTcwMjU3NjU3OCwicGF0aCI6Ii82NTk0ODcwNS8yOTA1NjM2ODMtODg4YWU0NmUtZGEwZi00NmYwLTg2ZDItYjZmYTA0MDE0N2EyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDE3NTYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3NGRhZTQ5YzA5NDBjOTIxZGIxMmQ2OTcxZjMwNDY3MDg3ZDJmZGVhZTg2OWZjNjAyNDg2NzdiNTE3MTg4MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i0el0WEH65fgB9dl_gAgo6tpwczjEu3LvUHmkS7o2aQ)
> 
> The current PR affects negatively the whole UI, making multiple panels full height and sometimes even affecting bottom bar position:
> 
>  Peek.2023-12-14.16-16.mp4

Strange, Are you sure are you building the right branch? It's working fine for me, Here is the video.
[Screencast from 14-12-23 11:31:30 PM IST.webm](https://github.com/CollaboraOnline/online/assets/61119120/4d7ac6ff-5974-4d0e-a959-2e303b3a6fc0)

2023-12-14 18:06 UTC, codewithvk commented
@pedropintosilva Can you please mention the height and width of the mobile screen that you tested in the above video?

2023-12-19 09:32 UTC, pedropintosilva commented on browser/css/device-mobile.css
> +	align-items: start;
snackbar misalignment

2023-12-19 09:42 UTC, pedropintosilva requested changes
I have tested again, double checked on real phone and on emulators. 

This fixes the issue, making dialogs (popups) such as insert hyperlink and insert comment full height and fixing the layout. Thanks.

Just 2 last things I have noticed:

# Snackbar misaligned


https://github.com/CollaboraOnline/online/assets/65948705/692c74d3-2531-48f1-8b30-314a03ff23c5

How to test it: add a breakpoint in `showSnackbar` and then trigger the snackbar by stopping collabora online with ctrl + c  in the terminal. Or by directly calling somewhere `showSnackbar` like so:

```diff
diff --git a/browser/src/control/Control.UIManager.js b/browser/src/control/Control.UIManager.js
index 0448642bce..4ff02dbf98 100644
--- a/browser/src/control/Control.UIManager.js
+++ b/browser/src/control/Control.UIManager.js
@@ -971,20 +971,10 @@ L.Control.UIManager = L.Control.extend({
 		}
 	},
 
 	enterReadonlyOrClose: function() {
-		if (this.map.isEditMode()) {
-			// in edit mode, passing 'edit' actually enters readonly mode
-			// and bring the blue circle editmode button back
-			this.map.setPermission('edit');
-			var toolbar = w2ui['actionbar'];
-			if (toolbar) {
-				toolbar.uncheck('closemobile');
-				toolbar.uncheck('close');
-			}
-		} else {
-			window.onClose();
-		}
+		// show snackbar on mobile: tap pencil and then the checkmark to save and close
+		this.showSnackbar(_('Server is now reachable. We have to refresh the page now.'), _('RELOAD'), function() {console.debug('snackbar');});
 	},
 
 	onGoBack: function(popStateEvent) {
 		if (popStateEvent.state && popStateEvent.state.context) {

```


# Busypopup

Ideally we would do a follow up on another PR, where we make sure the parent of the busypopup gets another css class so we can then add it to the exclusion pattern on the css side

| Before this PR | After this PR |
| --- | --- |
| ![localhost_9980_browser_3c909e4300_debug html_file_path=_home_pedro_LibreOffice_online-23-05_test_data_hello-world odt(Pixel 5)](https://github.com/CollaboraOnline/online/assets/65948705/811db968-4e25-4f1b-9a0a-f87ce37a571b) | ![Screen Shot 2023-12-18 at 14 43 27](https://github.com/CollaboraOnline/online/assets/65948705/5421339e-6f7d-42ad-b0a3-c1d6c1cb90cf) | 

# Snackbar

2023-12-21 17:27 UTC, codewithvk commented on browser/css/device-mobile.css
> +	align-items: start;
Updated PR.

2023-12-23 18:05 UTC, codewithvk commented
Created follow up PR to fix busy popup : ) PR: https://github.com/CollaboraOnline/online/pull/7891

2024-01-03 14:00 UTC, pedropintosilva approved these changes

2024-01-03 14:01 UTC, merged