Make sure to set the correct normalized view id for the tiles.
CollaboraOnline/online pull request #7775
Opened 2023-12-04 13:27 UTC by gokaysatir

When user switches to dark theme, previously requested tiles' normalizedViewIds may need to be updated.

Issue:
Users sometimes were getting tiles from the wrong theme.

Change-Id: Ie3324eb3f4879da5bfd0738513409e190422a9c0

* Resolves: # 
* Target version: master 

### Summary

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

2023-12-04 16:52 UTC, mmeeks requested changes
We should **never** trust a 'normalizedViewId' that comes from a client over a websocket. In fact - it's so bad doing that, that we should add code that wipes if it is not already there in our incoming ClientSession. Any TileCombine that comes in should have its normalizedViewId reset to the view's normalizedViewId. We should only believe such a view-Id when it comes from Kit itself.

Can you check that this never happens. Also - I'd love a unit test.

Thanks Gokay != =)

2023-12-05 13:00 UTC, gokaysatir commented
> We should **never** trust a 'normalizedViewId' that comes from a client over a websocket. In fact - it's so bad doing that, that we should add code that wipes if it is not already there in our incoming ClientSession. Any TileCombine that comes in should have its normalizedViewId reset to the view's normalizedViewId. We should only believe such a view-Id when it comes from Kit itself.
> 
> Can you check that this never happens. Also - I'd love a unit test.
> 
> Thanks Gokay != =)

Thank you for the review. I checked the implementation and saw that normalizedViewId is set by ClientSession before the "handleTileCombinedRequest" is called. I also changed the code to get it from the session in order to be on the safe side.

I will prepare a unit test now, can you have a second look when you have time?

2023-12-06 19:45 UTC, caolanm commented
There's a few normalized view id mismatch issues around at the moment. Is there a reproducible scenario for this one?

There was the theme-change-didn't-do-anything issue for core:
https://gerrit.libreoffice.org/c/core/+/159992

And there is also the https://github.com/CollaboraOnline/online/pull/7780 reconnect case which has a howto reproduce, and I'd like to consider them all together.

2023-12-07 09:14 UTC, gokaysatir commented
> There's a few normalized view id mismatch issues around at the moment. Is there a reproducible scenario for this one?
> 
> There was the theme-change-didn't-do-anything issue for core: https://gerrit.libreoffice.org/c/core/+/159992
> 
> And there is also the #7780 reconnect case which has a howto reproduce, and I'd like to consider them all together.

Yes it is still reproducible with latest core and online branches.

Reproducer:
* Open 2 views of the document.
* Start typing on one of them.
* Stop typing and quickly click on Dark Mode button.
* Somehow difficult to reproduce at first try but certainly possible.

![s4](https://github.com/CollaboraOnline/online/assets/28108660/aec9375e-0243-48b2-8530-cf13048335a9)

2023-12-07 09:23 UTC, gokaysatir commented
If i am reading the situation correctly (a timing issue), it will be difficult to write a unit test for this. I already created the unit test but it doesn't always fail :) It sometimes fails. Anyway, maybe someone can have a better idea before i am finished with the test. I haven't sent it yet, test is a mess for now.

2023-12-13 14:04 UTC, caolanm commented
> Any TileCombine that comes in should have its normalizedViewId reset to the view's normalizedViewId.

We appear to be doing this, we always setNormalizedViewI to the ClientSession one, but if we end up with unprocessed requests, f.e. after hitting tilesOnFlyUpperLimit limit and then get a theme change then the contents of ClientSession::_requestedTiles still have the old id

I guess it would also work to change whatever is pending in _requestedTiles when NormalizedViewId/CanonicalViewId changes.

Had a stab at making a test for this, but proving elusive so far.

2023-12-13 14:04 UTC, caolanm approved these changes

2023-12-13 14:05 UTC, merged