Fix view pushed up in Calc for autfilter popup
CollaboraOnline/online pull request #7832
Opened 2023-12-14 08:49 UTC by Darshan-upadhyay1110

- fix view jump by adding display `hidden` in js-dialog overlay 

Signed-off-by: Darshan-upadhyay1110 <darshan.upadhyay@collabora.com>
Change-Id: I4e48fd2d7363db53d4bf3a1d85f9897de3b1e91a

2023-12-14 13:38 UTC, Darshan-upadhyay1110 commented
@pedropintosilva i have tested  cases where we have Class  `jsdialog-overlay `
For ex : 
  - Format => Conditional format
  - Adding dropdown in Write using `Form`
  - some cases are in mobile-wizard that also looks good nothing breaks there for pop-ups
  
 All works okay
 
 Do you have any specific case to check for `jsdialog-overlay`  class ? let me know if any other than that it's good to go

2023-12-14 14:23 UTC, eszkadev commented
- all the popups in sidebar
- dropdowns like font, font size in notebookbar
- modal dialogs (warnings, errors)
- mobile-wizard
- autofilter
- mentions

2023-12-14 14:37 UTC, eszkadev commented
please add more detailed description for the commit message when possible: how to reproduce the problem it fixes

2023-12-14 14:40 UTC, eszkadev commented
I can confirm it fixes the "view pushing up" problem. But I see that this is caused because we stopped moving autofilter to be always fully visible. In the past it was not possible to have it like:
![auto](https://github.com/CollaboraOnline/online/assets/5307369/d87d446f-15e3-4fce-ac79-372c4f78b584)

2023-12-14 14:48 UTC, eszkadev approved these changes
For me it seems to be ok. @pedropintosilva ?

2023-12-14 15:28 UTC, pedropintosilva requested changes
hm, but having it then cropped is no bueno

2023-12-14 15:49 UTC, pedropintosilva reviewed
now it fixes for chrome and improves the situation for firefox. Meaning: for any browser it doesn't push the view but for FF it gets cropped

![image](https://github.com/CollaboraOnline/online/assets/65948705/66905cdb-8d60-4617-9bd0-803b301a3431)

2023-12-20 09:15 UTC, eszkadev approved these changes

2023-12-20 09:16 UTC, pedropintosilva approved these changes
I think we should merge. What do you think?

bottom line: the popover still can get cropped but it is a great improvement from before (the whole UI was being pushed upwards

2023-12-20 09:16 UTC, merged