Make browser/ clean before building
CollaboraOnline/online pull request #8225
Opened 2024-02-08 15:27 UTC by Minion3665

We create our bundle.js from our browser/dist/ directory, but this is not cleaned before building. Normally this is not an issue but occasionally we have a file that stops being there from one build to another (maybe it got deleted or there was a checkout). In this case the file persists in dist/ and still makes it into the new bundle.js. This is horrible in CI, but generally an exciting footgun at all times, and should be promptly removed.

Change-Id: Iadb69c5164cbc99062c14c8ce9de0ea5aa5d5680

* Resolves: # 
* Target version: master 

### Summary

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

2024-02-08 17:17 UTC, eszkadev approved these changes
Looks ok and Android passed now

2024-02-08 20:39 UTC, eszkadev commented
rebased, few times in row it failed with unit-integration, was not able to find file Rectangle.js

2024-02-09 11:48 UTC, Minion3665 commented
> rebased, few times in row it failed with unit-integration, was not able to find file Rectangle.js

looks like this was due to a leftover `tscompile.done`... as a bonus this file would have been left around after a `make -C browser clean-local` before too so this commit fixes that as well :)

2024-02-09 13:03 UTC, eszkadev requested changes
We can't do this on every `make run` to not lost additional content we copied into dist

2024-02-09 14:03 UTC, Minion3665 commented
Superseded by a CI change, I'll make another PR to fix the issue I noticed with `make clean-local` keeping tscompile.done

2024-02-09 14:03 UTC, closed without merging