Add Css rules for custom properties fields
CollaboraOnline/online pull request #8291
Opened 2024-02-16 14:20 UTC by meven

Signed-off-by: Méven Car <meven.car@collabora.com>
Change-Id: I4b57a1c04dc67620f4ee010e17fff4f9e677d0de (cherry picked from commit 8b2f8916b3490d273c3690125ad18aeb46d69924)

* Resolves: # 
* Target version: master 

### Summary

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

2024-03-11 09:32 UTC, pedropintosilva reviewed
Doesn't this need the `Allow Document properties tab custom properties for LOK` in the core 23 ?

2024-03-12 09:34 UTC, meven commented
> Doesn't this need the `Allow Document properties tab custom properties for LOK` in the core 23 ?

It does.
But this is not a hard-dependency (it can get in without any issue).

2024-05-07 19:37 UTC, eszkadev commented on browser/css/jsdialogs.css
> +#customprops .jsdialog .ui-grid .menubutton {
Master version is different (and better in my opinion, prevents applying to something different):
https://github.com/CollaboraOnline/online/blob/913f684e3023e1dc43a6c0ef99c8ff1428c74a88/browser/css/jsdialogs.css#L2077
`#customprops` -> `#DocumentPropertiesDialog #customprops`

2024-05-07 19:38 UTC, eszkadev requested changes
sync with master

2024-05-08 12:17 UTC, eszkadev approved these changes

2024-05-16 11:08 UTC, merged