browser: move  impl of savecomments command to Toolbar dispatch
CollaboraOnline/online pull request #8295
Opened 2024-02-16 15:30 UTC by meven

Signed-off-by: Méven Car <meven.car@collabora.com>
Change-Id: Ifcb34977b72bb0eccd23667deb4750637810e569 (cherry picked from commit 95cc0f6dd48303597bfdd5646990afb1fe615499)

* Resolves: # 
* Target version: master 

### Summary

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

2024-02-19 10:22 UTC, eszkadev approved these changes

2024-02-21 10:47 UTC, timar requested changes
Apaprently there was a wrong merge conflict resolution, and CI caught it.

2024-05-07 19:40 UTC, eszkadev commented on browser/src/control/Toolbar.js
> +		case 'savecomments':
`break;` needed above

2024-08-22 09:43 UTC, eszkadev commented
this is code cleanup, not a functional change, let's close as it is old stable branch

2024-08-22 09:43 UTC, closed without merging