Fix: DocumentRepair does not work for non-english
CollaboraOnline/online pull request #8322
Opened 2024-02-20 13:17 UTC by Darshan-upadhyay1110

- Do not use translated string `UNDO` and `REDO` as UNO command
- added action prop to handle above change in document repair file

To test
 - open document in non-English format
 - make some changes in the document
 - open document repair
 - try to perform REDO or UNDO ops

Change-Id: Ia98270b7623634fe4315988287445f14467df3f9

2024-02-21 15:56 UTC, timar requested changes
With this change 'Undo' and 'Redo' strings will not be extracted to pot file, and will be removed from translations with the next automatic update.

2024-02-22 06:31 UTC, Darshan-upadhyay1110 commented
@timar how can i test for next automated translation ? is there any README file ?

2024-02-22 06:43 UTC, timar commented
> @timar how can i test for next automated translation ? is there any README file ?

Use `make pot` in `browser/` directory to extract strings from files.

2024-02-22 06:44 UTC, timar approved these changes

2024-02-22 15:47 UTC, merged