writer: resize comments based on space
CollaboraOnline/online pull request #8663
Opened 2024-03-29 14:36 UTC by aszucs3

Make comments window bigger, if needed, and possible. Selected commits grow up to MAX size, even if there is no space for it.

There is 2 constant limitation:
MAX - --annotation-max-size this is the maximum size commentText window can grow. If the comment have more text, than it will have scrollbar.

MIN - --annotation-min-size if there is not enought space, but comment have more text, this is the minimum size of commentText window.

note: commentText window can be smaller then MIN, if it has less text.

During doLayout:
first, in resetCommentsSize comments size resets to default. (max-height = MIN size.)

after comments positioned with loopUp / loopDown,
resizeComments check all comments (maybe it could be optimized)

If a comment have more text as its actual size, then it check the space between this, and next comment.. and resize this comment.

If there is not enought space after the comment, then it check for more space between this, and previous comment, and resize + move up the comment as much as needed.

Change-Id: Ie7b0971febd8c965b01ebe23125eac4eded1a742

* Resolves: # 
* Target version: master 

### Summary

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

2024-04-03 12:48 UTC, eszkadev approved these changes
looks ok

2024-04-04 13:48 UTC, lpranam commented
Everything works fine but there is one issue with positioning.

Comment box should start from where the comment is inserted. 

I.e: in below screenshot long comment should be aligned with GlobalSessionMap. Otherwise it feels very confusing 

![Screenshot_20240404_191516](https://github.com/CollaboraOnline/online/assets/24812220/e65ff77e-cd0f-4187-8299-3cd27be180dd)

2024-04-04 13:48 UTC, lpranam requested changes
As explained in the other comment :)

2024-04-15 14:10 UTC, lpranam approved these changes

2024-04-15 14:10 UTC, merged