allow a test to start without sidebar
CollaboraOnline/online pull request #8904
Opened 2024-04-26 08:46 UTC by caolanm

instead of starting with sidebar and then removing it

Change-Id: If2ea433cd3d5fc18ad549bd3df095de15c126ad0

* Resolves: # 
* Target version: master 

### Summary

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

2024-04-26 20:18 UTC, neilguertincollabora commented
Another option I had to use for the annotation tests was to leave the sidebar out for the test but then expand the viewport so that the sidebar doesn't cover any content.

2024-05-08 08:00 UTC, caolanm commented
If I can do this then it will help to get a stable count of tiles requested between runs in future writer invalidation test improvements.

2024-05-08 12:55 UTC, neilguertincollabora requested changes

2024-05-08 19:47 UTC, neilguertincollabora approved these changes

2024-05-08 20:04 UTC, merged