Tokenize Quotes
CollaboraOnline/online pull request #8918
Opened 2024-04-28 23:56 UTC by NickWingate

* Resolves: #8103
* Target version: master 

### Summary

When ignoreQuotes = false delimiters within quotes (' or ") aren't tokenised.
Causes problems especially as space is the default delimiter, so if the input string has any `key="string"` pattern tokens a space will cause issues

For #8103 
Unocommand was being incorrectly tokenized as space is the default delimiter:

`uno .uno:ExecuteSearch {"SearchItem.SearchString":{"type":"string","value":" "}, ...`
`                                                                           ^^^`

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

2024-04-29 10:18 UTC, Ashod requested changes
Thanks, @NickWingate. This is a good bug to fix.

I worry about the efficiency of the code, though. Given how frequently the tokenizers are called, we really can't afford to have an algorithm that's not linear. I left some notes and tips, but please feel free to reach out if need further help. Re-writing these functions to be optimal might not be trivial, so I suggest splitting them, since it seems we only care about supporting quotes in exactly one case. That single case can be less efficient, until we improve the implementation. I just don't want to make all the command processing code slower because of that single case.

2024-04-29 10:18 UTC, Ashod commented on common/StringVector.hpp
> +                         std::vector<StringToken>& tokens, bool ignoreQuotes = true)
I'm not a fan of reusing function with default parameters. They make maintenance harder later on.

I also worry about the cost of the new logic. These tokenerizers are heavily used for each and every command, and multiple times at that. Perhaps we should consider separating the cases where we expect quotes vs those that we never support quotes and have separate implementations?

2024-04-29 10:18 UTC, Ashod commented on common/StringVector.hpp
> +        if(delimiterString.find('\'') != std::string::npos || delimiterString.find('"') != std::string::npos)
Please use clang-format (you can configure your editor to run it on *modified* lines upon save).

2024-04-29 10:18 UTC, Ashod commented on common/StringVector.hpp
> +            if (end != std::string::npos) {
Please observe the coding convention used throughout the C++ codebase. Use clang-format to help with formatting.

2024-04-29 10:18 UTC, Ashod commented on common/StringVector.hpp
> +        std::string delimiterString(delimiter);
We should use `strchr` to search for a single character in a C-string (https://en.cppreference.com/w/c/string/byte/strchr). Creating a `std::string` is unnecessarily inefficient in this case.

2024-04-29 10:18 UTC, Ashod commented on common/StringVector.hpp
> +                singleQuotesBefore = std::count(s.begin(), s.begin() + end, '\'');
Very costly to do this when `ignoreQuotes` is true. Also, isn't it better to do `find_first_of("\'\"", searchStart, end - searchStart + 1);`

(Actually, the more efficient way to implement support for quotes is to do the search inline. That is, to go through each character and see if it's one of the quotes or the delimiter, and act accordingly. That would at least be a single linear search, where now this algorithm is at least quadratic. But, perhaps it's best to split this into two implementations, the old one that doesn't support quotes, and a new one that might be inefficient but supports quotes.)

2024-04-29 10:18 UTC, Ashod commented on common/StringVector.hpp
> +            if (ignoreQuotes || (singleQuotesBefore % 2 == 0 && doubleQuotesBefore % 2 == 0) ||
A better algorithm is to find either the delimiter or a quote. If the quote is before the delimiter, then search for the matching quote before searching for the delimiter again, or the end of string. There shouldn't be a need to count quotes (note that counting is a side-effect of the unnecessary quadratic algorithm).

2024-05-25 12:26 UTC, Ashod commented
> Made a new function `tokenize_outside_quotes` for handling cases where the data may have quotes. Also changed to a new algorithm as suggested: go character by character and when a quote is found stop looking for the delimiter until quote is closed. When the delimiter is character this is simple, when the character is a string we use `s.substr(i, len) == delimiter` to compare.

Thank you, @NickWingate, for the update.

I went through the code, but, before commenting on the code, I'm wondering why there is no test with the reported issue of searching for `"  "` (two spaces). Shouldn't one expect that if this resolves the reported issue, and assuming the issue is related to a bug in the tokenizer, that a test would include a reproducer of said issue?

Also, I don't understand why we have implemented so many variations of the tokenizer when it would seem that we only use one. Perhaps I missed something, but I don't see the code using all these variations.

Finally, if we have to implement a tokenizer that takes quotes into account, why do we care to implement a special version for when there are no quotes? Is that an optimization? Have we measured the three versions?

Thank you.

2024-07-23 12:52 UTC, NickWingate commented
>I went through the code, but, before commenting on the code, I'm wondering why there is no test with the reported issue of searching for `" "` (two spaces). Shouldn't one expect that if this resolves the reported issue, and assuming the issue is related to a bug in the tokenizer, that a test would include a reproducer of said issue?

Yes, good point. I will add the test.

>Also, I don't understand why we have implemented so many variations of the tokenizer when it would seem that we only use one. Perhaps I missed something, but I don't see the code using all these variations.

No, I just created further overloads of `tokenize_outside_quotes` where the original `tokenize` has these overloads already so if someone has a similar issue, but when using string delimiter instead of a char delimiter they can use this function without rewriting the `tokenize`. It seemed sensible at the time, but if you think this is just bloat I can remove it.

>Finally, if we have to implement a tokenizer that takes quotes into account, why do we care to implement a special version for when there are no quotes? Is that an optimization? Have we measured the three versions?

I did this as suggested:
>Re-writing these functions to be optimal might not be trivial, so I suggest splitting them, since it seems we only care about supporting quotes in exactly one case

In each `tokenize_outside_of_quotes` we check that if the delimiter is/contains a quote then default back to the normal `tokenize`. I thought this was easiest solution for now but if you have a better idea I can implement that instead?

2025-05-01 12:14 UTC, caolanm commented
The delim tokens are collapsed together. so using tokens.cat(' '...) doesn't get the original string back .

The StringVector keeps the original string, so if we have something like substrFromToken(int index) and used that to get the "remainder" of the string instead of tokens.cat(' ', 2) (in dialogEvent and unoCommand) then that would probably work too.

2025-05-01 13:17 UTC, caolanm approved these changes
lets merge this as is then

2025-05-01 13:17 UTC, merged