jsdailog:css: increase jsdialog width to fit content
CollaboraOnline/online pull request #9067
Opened 2024-05-15 23:11 UTC by lpranam

increased jsdialog width to fit content when necessary. max width is set to 1000px because some other dialog(i.e: Zotero) already uses tree widget width 800px which makes the entire dialog approx 990px.

removed margin from icon to make it look even spaced in listview (i.e: manage changes, zotero add citation)

Change-Id: I225b5b5d42d573cb4afcdb428e2eb3b81aa99073

* Target version: master 

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

2024-05-20 09:05 UTC, pedropintosilva commented
Thank you @lpranam but with this commit specifically when using max-content which padding and surrounding context, granted you used also max-width to limit the side effects of that. Nevertheless the content is not wrapping (until it reaches the max-width). This in turn seems to make every jsdialog quite wide.

| With this commit | Before |
| --------------------------| --------- |
| ![image](https://github.com/CollaboraOnline/online/assets/65948705/b8fd0d55-7139-4d34-a936-979f761337b0) | ![image](https://github.com/CollaboraOnline/online/assets/65948705/caebe0d5-f8ea-41f2-8969-9ad029d88e74) |

2024-05-21 23:33 UTC, lpranam commented
Now it should only affect manage changes dialog :)

2024-05-21 23:33 UTC, lpranam commented
Now it should only affect manage changes dialog :) @pedropintosilva

2024-05-23 13:17 UTC, pedropintosilva requested changes
thanks.
It still affects other places introducing the lack of space regression in places like navigator or function wizard:

![image](https://github.com/CollaboraOnline/online/assets/65948705/24e1d704-88cf-4d06-95cd-cfdcd7979c4e)

2024-05-27 11:02 UTC, pedropintosilva approved these changes
Thanks

2024-05-28 16:00 UTC, merged