Add Invert Background Color buttons
CollaboraOnline/online pull request #9086
Opened 2024-05-17 08:56 UTC by GulsahKose

We have that button for Writer, Calc, Draw, Impress menubar and notebookbar

Change-Id: I745c010749b8c5b88c0d181418f2a47921a94620

* Resolves: #9061
* Target version: master 

### Summary

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

2024-05-17 09:01 UTC, pedropintosilva requested changes
Thanks! Please use a short label , drop `Document` so, `Invert Background`

2024-05-17 17:34 UTC, timar commented on browser/src/control/Control.Menubar.js
> +                   {name: _('Invert Background'), id: 'invertbackground', type: 'action'},
please use tabs not spaces to indent

2024-05-17 17:34 UTC, timar commented on browser/src/control/Control.Menubar.js
> +                   {name: _('Invert Background'), id: 'invertbackground', type: 'action'},
please use tabs not spaces to indent

2024-05-17 17:34 UTC, timar commented on browser/src/control/Control.NotebookbarCalc.js
> +            {
please use tabs not spaces to indent

2024-05-17 17:35 UTC, timar commented on browser/src/control/Control.NotebookbarImpress.js
> +            {
please use tabs not spaces to indent

2024-05-17 17:35 UTC, timar commented on browser/src/control/Control.UIManager.js
> +    },
please use tabs not spaces to indent

2024-05-20 11:37 UTC, pedropintosilva approved these changes

2024-05-20 11:38 UTC, merged