wsd: added config option for background manualsave
CollaboraOnline/online pull request #9089
Opened 2024-05-17 12:05 UTC by Rash419

Change-Id: I76de35fe9b4135b74a96436f0c9a3245f4e00bd9

* Target version: master

2024-05-17 13:25 UTC, mmeeks requested changes
We also need to dig into the wopi save unit test to see what is going on there. Perhaps it is best to get this setting included - but disabled initially as/when you've cleaned up the comment =)

Thanks!

2024-05-17 13:25 UTC, mmeeks commented on wsd/DocumentBroker.cpp
> -    bool background = forceBackgroundSave || (autosave && _backgroundAutoSave);
So - for the very last save of the document - we don't want to do a background save. Can you check from the logs that if you modify a document, then close the window without saving - that the final 'force' save is not a background save - even with the settings turned on.

Thanks!

2024-05-18 10:35 UTC, mmeeks commented
I'll work on finishing and merging this then.

2024-05-20 07:16 UTC, Rash419 commented
closing this in favor of https://github.com/CollaboraOnline/online/pull/9098

2024-05-20 07:16 UTC, closed without merging