calc: don't jump to own cursor if not looking
CollaboraOnline/online pull request #9170
Opened 2024-05-28 14:08 UTC by eszkadev

If we have cell selected on the bottom of the sheet and we scroll up to watch something else so we don't see the cursor: if other user will add row above - we will jump to our own cursor. It's because it changed the address: like A500 to A5001.

Let's don't do that. Solution could be to enter "non following" mode when we scroll outside our own cursor. So we will not jump to our cell if not needed. Then if we click or do any key press - we should cancel that mode and go back to "following own cursor mode".

This can be additionaly marked by something on the user list.

2024-06-20 05:40 UTC, eszkadev commented
hi, @gokaysatir & @Minion3665 could you look at some point - this patch needs other eyes and manual testing :)

Affects:
- following users / editor
- scrolling in calc

2024-06-21 07:21 UTC, gokaysatir approved these changes
Code seems ok and works beautifully for me, thanks :)

2024-06-21 09:19 UTC, Minion3665 requested changes
This patch seems to stop me from unfollowing someone by typing (I tested in Calc) ... (there's also a following problem where the unfollowed state still shows in the chip and is called "Following You", but I think this is an earlier regression)

2024-06-21 10:11 UTC, Minion3665 approved these changes
working for me now and the change looks good, thanks!

2024-06-21 11:02 UTC, eszkadev commented on browser/src/layer/tile/CanvasTileLayer.js
> +		var isFollowingOwnCursor = parseInt(app.getFollowedViewId()) === parseInt(this._viewId);
done

2024-06-21 12:34 UTC, merged