Cypress: Mobile calc: nonexistent #test-div-cell_selection_handle_start
CollaboraOnline/online pull request #9194
Opened 2024-05-31 10:22 UTC by pedropintosilva

I have noticed by looking at one of the PRs
https://github.com/CollaboraOnline/online/pull/9186 that this
unrelated test is failing.

I have tested locally and indeed, sometimes it fails. It seems it
tries to check for '#test-div-cell_selection_handle_start' but I
couldn't find it either. But I did find '.text-selection-handle-start'

Change-Id: I1daec0df5b8135935127b1de1348458b288c2d51

---

Here is the breakdown (v passes, x fails):

Mobile: calc/cell_appearance_spec.js
 Apply left and right border
- [v] cGet input#addressInput-input
   - log<< removeTextSelection - end
   [Comment] ^ from calc_helper.js:removeTextSelection()
- [x] cGet#test-div-cell_selection_handle_start
  - expected #test-div-cell_selection_handle_start to exist in the DOM
  [Comment] ^ Called in the calc_helper.js:helper.doIfOnMobile()

----

Signed-off-by: Pedro Pinto Silva <pedro.silva@collabora.com>

2024-06-01 07:40 UTC, codewithvk approved these changes

2024-06-06 07:51 UTC, gokaysatir commented
This issue may mean that the object is visible but the section visibility is set to false.
I'll need to check this.

2024-06-11 09:24 UTC, gokaysatir requested changes
The issue might have been solved with the recent improvements, mentioned PR seems to have passed the cypress tests.

I think we don't need this PR.

2024-06-21 12:33 UTC, pedropintosilva commented
@gokaysatir at the time I inspected the DOM looking at the whole HTML structure (including hidden elements) and nowhere we were creating an element with a **css class** `text-selection-handle-start` but we do create an element with the **id** `text-selection-handle-start`

2024-06-22 20:02 UTC, gokaysatir commented
> @gokaysatir at the time I inspected the DOM looking at the whole HTML structure (including hidden elements) and nowhere we were creating an element with a **css class** `text-selection-handle-start` but we do create an element with the **id** `text-selection-handle-start`

I think you meant with class, not id? Because your patch replaces id with class name.

Anyway, i see your point, so it means that the object is not visible. Because if the object is not visible "the test div gets deleted" if i remember correctly. There may be some divs with classes but doesn't matter, the visibility check can be done correctly with test-divs.

I think CI is fine so far, can we keep this out for some time? If we see failures then we can always get this in.

2024-06-25 07:41 UTC, closed without merging

2024-06-25 07:43 UTC, pedropintosilva commented
> > @gokaysatir at the time I inspected the DOM looking at the whole HTML structure (including hidden elements) and nowhere we were creating an element with a **css class** `text-selection-handle-start` but we do create an element with the **id** `text-selection-handle-start`
> 
> I think you meant with class, not id? Because your patch replaces id with class name.
> 
> Anyway, i see your point, so it means that the object is not visible. Because if the object is not visible "the test div gets deleted" if i remember correctly. There may be some divs with classes but doesn't matter, the visibility check can be done correctly with test-divs.
> 
> I think CI is fine so far, can we keep this out for some time? If we see failures then we can always get this in.

yes my mistake while typing, amended my comment. 

Understood. Closed this PR