Use Workers to do tile decompression and unpremultiply
CollaboraOnline/online pull request #9208
Opened 2024-06-03 14:49 UTC by Cwiiis

* Resolves: # 
* Target version: master 

### Summary

Two patches; the first fixes a bug where if we receive new keyframe tiledata and need to ensure the canvas, we end up decompressing/unpremultiplying/putting the old data unnecessarily (I think). The second uses a worker to offload the majority of tile image data decompression and unpremultiplying from the main thread and improves response during large update operations (such as scrolling through a document).

The code is not properly formatted yet, I'm opening this PR now and will update it with fixes once I figure out what those fixes are...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

2024-07-26 16:14 UTC, mmeeks requested changes
Ok - this needs more work; I don't think we can merge it as-is I'm afraid.

2024-07-26 16:14 UTC, mmeeks commented on browser/src/core/SocketWorker.js
> +	importScripts('../layer/tile/CanvasTileUtils.js');
I suspect that this has not been tested with a bundlified product build (?) or do we distribute CanvasTileUtils.js on its own ?

2024-07-26 16:14 UTC, mmeeks commented on browser/src/layer/tile/CanvasTileUtils.ts
> +					data[i] = Math.ceil((data[i] * 255) / alpha);
We should probably use a 64k byte lookup table here as some of the core LibreOffice code does =)

2024-07-26 16:14 UTC, mmeeks commented on browser/src/layer/tile/CanvasTileUtils.ts
> +						this.lastPixel.set(data.subarray(pixSrc, pixSrc + 4));
I thought we decided that subarray was unfeasibly slow on firefox, and we didn't want to over-use it ?

2024-07-26 16:14 UTC, mmeeks commented on browser/src/core/Socket.js
> +			this._queueWorkerTileProcessing(e);
Am I reading this right that we take 'tile:' messages only - and we potentially then emit them out of order with subsequent 'delta:' and 'update:' messages which could arrive before the tiles are de-compressed by the thread - that is likely to lead to corrupted pixels.
Hmm.

2024-10-04 11:00 UTC, Cwiiis commented
I'm going to close this as I have a newer, better version of the patch in a different branch. I'll likely need advice resolving some of these comments - I'll try to flag these issues explicitly.

2024-10-04 11:00 UTC, closed without merging