Use link color comes from core instead config
CollaboraOnline/online pull request #9441
Opened 2024-07-05 12:18 UTC by GulsahKose

This patch is dependent to core patch that sends true link color for online cliens according to they are in dark mode or bright mode.

Change-Id: I7b819e9619a1254176424d85af2fd5c12c28f483

* Resolves: # 
* Target version: master 

### Summary

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

2024-07-05 13:05 UTC, eszkadev commented
best to put links to related tickets in the description so it is easy to find it

2024-07-05 13:11 UTC, GulsahKose commented
If you mean that, I'll update the commit message with core patch hash when core patch is merged.

2024-07-05 13:13 UTC, pedropintosilva commented
https://gerrit.libreoffice.org/c/core/+/169984

2024-07-05 13:15 UTC, eszkadev requested changes

2024-07-05 13:15 UTC, eszkadev commented on coolkitconfig.xcu
> -                <value>1939955</value>
we want to keep it here and not hardcode in the core I think

2024-07-05 13:17 UTC, eszkadev commented
i think it will be fixed in core-only patch

2024-07-05 13:23 UTC, GulsahKose commented
> i think it will be fixed in core-only patch

Yes i testednow only core patch works too.

2024-07-10 13:51 UTC, eszkadev commented
core patch will be enough

2024-07-10 13:51 UTC, closed without merging