Mobile: Modify 'insert comment' icon
CollaboraOnline/online pull request #965
Opened 2020-12-10 20:10 UTC by umutbayramoglu

Signed-off-by: umutbayramoglu <umut265@gmail.com>
Change-Id: I18048fcd84345032d7a2a4fb0d52a4505fb4f0d7

* Resolves: # 
* Target version: master 

### Summary
Use **plus** instead of **three dots** as the inner shape for the insert comment icon.

### TODO

- [ ] ...

### Checklist

- [x] Code is properly formatted
- [x] All commits have Change-Id
- [x] I have run tests with `make check`
- [x] I have issued `make run` and manually verified that everything looks okay
- [x] Documentation (manuals or wiki) has been updated or is not required

2020-12-14 09:10 UTC, pedropintosilva commented
Thanks! I have noticed that the plus sign is not centred (vertically) aligned to the rounded rectangle that composes the outer-shape. Could you please amend that? (here is my fix: https://github.com/CollaboraOnline/online/commit/f9ae5f2dae8c23c0e6093699d2ad33a11b91c8b4 )

2020-12-14 15:15 UTC, pedropintosilva requested changes
https://github.com/CollaboraOnline/online/pull/965#issuecomment-744296254

2020-12-14 15:41 UTC, umutbayramoglu commented
I updated PR. Thank you @pedropintosilv.

2020-12-15 13:24 UTC, pedropintosilva approved these changes

2020-12-15 13:25 UTC, merged