leaflet: prevent entering non numeric value in spin field
CollaboraOnline/online pull request #974
Opened 2020-12-13 18:56 UTC by lpranam

Signed-off-by: Pranam Lashkari <lpranam@collabora.com>
Change-Id: I78403b489f8057b3131e1ccc1cbeef74377bedc4

* Target version: master 

### Summary
In safari, firefox and in ios app user could enter non-numeric characters in the spin field, this patch prevents it.

### Checklist

- [ ] Code is properly formatted
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

2020-12-14 09:22 UTC, eszkadev requested changes

2020-12-14 09:22 UTC, eszkadev commented on loleaflet/src/control/Control.MobileWizardBuilder.js
> +		this._controlHandlers['PreventNonNumericalInput'] = this._spinFieldPreventNonNumericalInput;
I think we shouldn't add it here as _controlHandlers should contain only functions building widgets with specific arguments (parent, data, builder)

2020-12-14 09:22 UTC, eszkadev commented on loleaflet/src/control/Control.MobileWizardBuilder.js
> +		spinfield.onkeypress = this.PreventNonNumericalInput;
and use builder.PreventNonNumericalInput here

2020-12-14 10:20 UTC, eszkadev commented on loleaflet/src/control/Control.MobileWizardBuilder.js
> +		if (!charStr.match(/^[0-9.]+$/))
one more thing: in some languages "," is used instead of "."

2020-12-14 11:31 UTC, tzolnai commented
Hi,
I think cypress tests fail because we use the `ENTER` character to accept the typed input, which is discarded by this `_preventNonNumericalInput` method, as I see. You can use `L.Browser.cypressTest` bool value to accept `ENTER` character for cypress tests only and later we can make cypress simulation closer, how these input fields work on mobile.  Also, the question is what happens on mobile, when you push the ready/accept button after you typed the number in these fields? Does it work after this change? I wonder whether this mobile ready/accept button is also typed as an `ENTER` character or is it handled on a completely different way?

2020-12-29 10:15 UTC, eszkadev approved these changes

2020-12-29 10:15 UTC, merged