private/pedro/status bar search btns disable status
CollaboraOnline/online pull request #9766
Opened 2024-08-09 14:26 UTC by pedropintosilva

- **Status bar: Enable/disable search buttons**
- **Status bar: Make cancel search icon more subtle**

2024-08-09 14:41 UTC, eszkadev commented on browser/src/control/Control.StatusBar.js
> +			this.enableItem('searchprev-button', false);
I think it is a workaround. We should always use "id" in this case "searchprev" only. Probably we have some bad code in the enable/disable implementation

2024-09-05 14:18 UTC, pedropintosilva commented
This seems quite serious to don't merge. I prefer to have functional search buttons ASAP then wait for the ideal approach here.

2024-09-05 15:30 UTC, gokaysatir approved these changes
Yep, sorry @pedropintosilva. Let me approve the request. Then we'll have a follow up for even better improvements :)

2024-09-05 19:23 UTC, eszkadev requested changes
sorry, I really think it's some fundamental problem we should fix...

2024-09-05 19:30 UTC, eszkadev commented
I think we fail here: https://github.com/CollaboraOnline/online/blob/master/browser/src/control/Control.JSDialogBuilder.js#L2942
the example item is: `{type: 'customtoolitem',  id: 'searchprev', command: 'searchprev', text: _UNO('.uno:UpSearch'), enabled: false, pressAndHold: true},`
which has implementation in: https://github.com/CollaboraOnline/online/blob/master/browser/src/control/Control.JSDialogBuilder.js#L2499
which uses `_unoToolButton`
and this leads to https://github.com/CollaboraOnline/online/blob/master/browser/src/control/Control.JSDialogBuilder.js#L2291  where `-button` is present

And that is not the root node. The rule is: we only execute action on the root node of widget (in this example: `div`).
So it is not applied to the button itself. To solve that problem we have helper which synchronizes state with the root node:
eg. `JSDialog.SynchronizeDisabledState(div, [spinfield]);`

2024-09-05 19:37 UTC, eszkadev approved these changes

2024-09-06 06:55 UTC, pedropintosilva commented
Cypress (desktop)
```
 Table operations
       Set minimal row height.:
     AssertionError: Timed out retrying after 10000ms: expected '[ <td>, 5 more... ]' not to have attribute 'height'
```

unrelated, re-try

2024-09-06 07:36 UTC, pedropintosilva commented
Thanks, but now without my changes and with your commit @eszkadev I now see the next and prev buttons again disabled:

![image](https://github.com/user-attachments/assets/7ea5ee47-9bc2-4129-9e85-b8e4173c4668)

I wonder,  and since @gokaysatir was already reviewing, if you @eszkadev would prefer @gokaysatir to take this from you

2024-09-06 08:05 UTC, eszkadev commented
yes, @gokaysatir  please check

2024-09-06 13:56 UTC, gokaysatir commented
@eszkadev can you have a look at the last commit when you have time? I think "disabled" class usage is being removed from some of the widgets. unotoolbuttons seem to be one of them.

2024-09-06 13:56 UTC, gokaysatir approved these changes

2024-09-06 14:40 UTC, eszkadev commented
yes, it seems we use attribute now: https://github.com/CollaboraOnline/online/blob/master/browser/src/control/Control.JSDialogBuilder.js#L2978

2024-09-06 14:42 UTC, eszkadev commented
thanks, seems to work now :)

2024-09-06 15:39 UTC, merged