Impress UI: Turn notes view and normal view buttons into big tool ite…
CollaboraOnline/online pull request #9845
Opened 2024-08-19 10:02 UTC by gokaysatir

…m buttons.

Change-Id: I7088382d9319c4b8119708c55c2e7c027bc2efe1

* Resolves: # 
* Target version: master 

### Summary

### TODO

- [ ] ...

### Checklist

- [ ] I have run `make prettier-write` and formatted the code.
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

2024-08-22 08:52 UTC, eszkadev requested changes

2024-08-22 08:52 UTC, eszkadev commented on browser/images/lc_view-normal-view.svg
we should prefer filename based on uno command, it is the priority to get icon name and also used by other components like sidebar. id defined in nb can not match

2024-08-22 09:27 UTC, gokaysatir commented on browser/images/lc_view-normal-view.svg
But it doesn't match with the uno-command-names?

2024-08-23 09:17 UTC, pedropintosilva commented
I have amended the commit to don't rename the svg. So it says the same name as the uno command. I have tested.

2024-08-26 08:35 UTC, eszkadev approved these changes
looks ok

2024-08-26 08:37 UTC, gokaysatir commented
> this is a good improvement, thanks. As a follow up PR I would love to
> 
> * Have solely one button 'Notes View' that is a toggle (on/off). Otherwise, it's quite cumbersome for the user to understand what to press to be able to exit the notes view
> * When switching between views the Active tab shouldn't change.
> 
> Note: Currently I'm unable to exist the notes view no matter if I press the notes or the normal view buttons (on Firefox, master)

Thanks @pedropintosilva :) I will create an internal task for the additional improvements.

2024-08-26 08:41 UTC, merged