scrollWindow: fix view scrolling
CollaboraOnline/online pull request #9869
Opened 2024-08-21 13:24 UTC by meven

Change-Id: I54990645d17e1e352397f1d57b4cc671af6b5839

* Resolves: #9770
* Target version: master 

### Summary

 * make scrollWindow height fix
 * special case data.horizontal.page_size == 0
 * improve computation of rowHeight
 * don't resize dynamically dimensions based on dom changes

### Checklist

- [x] I have run `make prettier-write` and formatted the code.
- [x] All commits have Change-Id
- [x] I have run tests with `make check`
- [x] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

2024-08-21 15:33 UTC, caolanm commented on browser/src/control/jsdialog/Widget.ScrolledWindow.js
> +	let drawingArea = _hasDrawingAreaInside(data.children)
The auto-bot has a good point here about a missing semicolon on this line

2024-08-22 08:35 UTC, eszkadev commented
It works nice in most of the cases, but still has problems with vertical scrolling in "managed by user" mode.

[symbols-2024-08-22_10.33.22.webm](https://github.com/user-attachments/assets/f21ea35a-3b81-4c11-98a6-5926c0f7e5c1)

It worked in the past before regression commit, it was also not doing "scrolling animation" so UI looked less buggy/jumping.

2024-08-22 08:38 UTC, eszkadev requested changes
please try to fix vertical scrolling

2024-08-22 10:12 UTC, meven commented
The use cases to test:

In calc:
 * function wizard, select AGGREGATE and try to scroll
 * insert symbol
 * properties > custom properties tab.

2024-08-30 06:59 UTC, eszkadev commented
This works bad:
[scroll-2024-08-30_08.54.08.webm](https://github.com/user-attachments/assets/6b567266-56e3-4d9f-8768-2edc2fed5c89)

I used keyboard (arrow down) in symbol dialog.

Please see how it works with the reverted version (current master):
[scroll-2024-08-30_08.57.03.webm](https://github.com/user-attachments/assets/931c3a9b-fa58-4eef-a589-a94b48cb1dd0)

Can we just setup the size of scroll window in the file properties dialog for custom properties using CSS?
I think behavior now is ok, only look of custom properties tab is not good.

2024-09-02 09:10 UTC, meven commented
> Can we just setup the size of scroll window in the file properties dialog for custom properties using CSS?

The content size is dynamic in the custom properties and function wizard, there it is not possible and in the symbol dialog it would break when we add new symbols.

2024-09-02 09:10 UTC, meven commented
> This works bad: [scroll-2024-08-30_08.54.08.webm](https://github.com/user-attachments/assets/6b567266-56e3-4d9f-8768-2edc2fed5c89)
> 
> I used keyboard (arrow down) in symbol dialog.

I noticed it, I have an idea how to fix that.

2024-09-03 12:57 UTC, meven commented
> Really isn't it enough to fix custom properties sizing on top of current master ?
> Like some CSS: to make scroll-window height depending on height of the dialog and rest of the items static.

My patches sets the scroll-window "view" height, in `browser/css/jsdialogs.css`.
But that's the content-height that's dynamic.

2024-10-11 16:18 UTC, eszkadev commented
not needed currently: other PR was merged

2024-10-11 16:18 UTC, closed without merging