Attempt to use a more precise filter for time field.
CollaboraOnline/online pull request #9872
Opened 2024-08-21 13:53 UTC by gokaysatir

Change-Id: I1eb77f0345db74b7cd656fbb853c6a10567d1e63

* Resolves: # 
* Target version: master 

### Summary

### TODO

- [ ] ...

### Checklist

- [ ] I have run `make prettier-write` and formatted the code.
- [ ] All commits have Change-Id
- [ ] I have run tests with `make check`
- [ ] I have issued `make run` and manually verified that everything looks okay
- [ ] Documentation (manuals or wiki) has been updated or is not required

2024-08-21 14:29 UTC, eszkadev requested changes
This change breaks spinfields: no up/down arrow is shown, eg in the Impress sidebar.
Please also add more details into commit message - where to test and what it does (which cases it fixes).
If value is preformatted in the core - we probably need to show it as regular text, not spinfield. But regular spinfields need to be real spinfield to show correct ui on mobile.

![spinfield](https://github.com/user-attachments/assets/119d05b0-0dda-4815-9be7-6782ecd1b897)

2024-08-22 09:55 UTC, eszkadev commented
> Please also add more details into commit message - where to test and what it does (which cases it fixes). If value is preformatted in the core - we probably need to show it as regular text, not spinfield. But regular spinfields need to be real spinfield to show correct ui on mobile.

could you add details how to test, what it changes?

2024-08-22 10:25 UTC, gokaysatir commented
> > Please also add more details into commit message - where to test and what it does (which cases it fixes). If value is preformatted in the core - we probably need to show it as regular text, not spinfield. But regular spinfields need to be real spinfield to show correct ui on mobile.
> 
> could you add details how to test, what it changes? + link to core change or at least title

Yep, thanks for checking :) Added more detailed explanation.

2024-08-22 11:46 UTC, eszkadev commented on browser/src/control/Control.JSDialogBuilder.js
> +		if (data.hasTimeFormatter) {
did you find any field which uses this condition?

I looked again and it seems widget with `"type"="time"` uses `JSDialog.timeField`, and it's the only widget which can trigger this condition... so probably it's leftover code from before we introduced `JSDialog.timeField`

2024-08-22 11:47 UTC, eszkadev commented on browser/src/control/Control.JSDialogBuilder.js
> +		if (data.hasTimeFormatter) {
File -> Properties -> Custom properties with field type date time has it it seems

2024-08-22 12:56 UTC, merged